// Generated by zig-php AOT compiler
// DO NOT EDIT

const std = @import("std");
const runtime = @import("runtime_lib.zig");

// String table
const string_table = [_][]const u8{
    "CallableClass",
    "add",
    "int",
    "$a",
    "$b",
    "=== First-class callable ===\n",
    "$obj",
    "$add",
    "args",
    "add(5, 3): ",
    "\n",
    "__arrow_2",
};

// 静态字符串池（运行时初始化一次）
var static_strings: [string_table.len]*runtime.PHPString = undefined;
var static_strings_initialized = false;

fn initStaticStrings() void {
    if (static_strings_initialized) return;
    for (string_table, 0..) |str, i| {
        static_strings[i] = runtime.PHPString.initStatic(str);
    }
    static_strings_initialized = true;
}


// MARKER: generateFunction called
pub fn @"CallableClass::add"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) !runtime.Value {
    _ = &ctx;
    const __prev_call_args = runtime.setCurrentCallArgs(args);
    defer runtime.restoreCurrentCallArgs(__prev_call_args);
    _ = allocator;
    _ = runtime;
    if (runtime.findClass("CallableClass")) |__class_meta| {
        const __prev_scope = runtime.getCurrentScopeClass();
        runtime.setCurrentScopeClass(__class_meta);
        defer runtime.setCurrentScopeClass(__prev_scope);
        if (runtime.getCurrentCalledClass() == null) {
            runtime.setCurrentCalledClass(__class_meta);
        }
    }
    runtime.profiler.enterGlobal("CallableClass::add");
    defer runtime.profiler.exitGlobal("CallableClass::add");
    // Register declarations
    var reg_7: runtime.Value = runtime.Value.initNull();
    _ = &reg_7;
    var reg_1_storage: runtime.Value = runtime.Value.initNull();
    var reg_1: *runtime.Value = &reg_1_storage;
    _ = &reg_1;
    var __def_1: bool = false;
    _ = &__def_1;
    var reg_0: runtime.Value = runtime.Value.initNull();
    _ = &reg_0;
    var reg_4: runtime.Value = runtime.Value.initNull();
    _ = &reg_4;
    var reg_6: runtime.Value = runtime.Value.initNull();
    _ = &reg_6;
    var reg_8: runtime.Value = runtime.Value.initNull();
    _ = &reg_8;
    var reg_5: runtime.Value = runtime.Value.initNull();
    _ = &reg_5;
    var reg_2_storage: runtime.Value = runtime.Value.initNull();
    var reg_2: *runtime.Value = &reg_2_storage;
    _ = &reg_2;
    var __def_2: bool = false;
    _ = &__def_2;
    var reg_3_storage: runtime.Value = runtime.Value.initNull();
    var reg_3: *runtime.Value = &reg_3_storage;
    _ = &reg_3;
    var __def_3: bool = false;
    _ = &__def_3;

    var null_val = runtime.Value.initNull();
    _ = &null_val;

    // Instructions
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:3
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 3);
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:3
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 3);
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:3
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 3);
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:3
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 3);
    reg_0 = ctx;
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:3
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 3);
    reg_1.*.release(runtime.runtime_allocator);
    _ = reg_0.retain();
    runtime.val_assign(reg_1, reg_0);
    __def_1 = true;
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:3
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 3);
    reg_4 = if (args.len > 0 and !args[0].isMissing()) runtime.Value.initInt(args[0].toInt()) else runtime.Value.initInt(0);
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:3
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 3);
    reg_2.*.release(runtime.runtime_allocator);
    runtime.val_assign(reg_2, runtime.Value.initInt(reg_4.toInt()));
    __def_2 = true;
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:3
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 3);
    reg_5 = if (args.len > 1 and !args[1].isMissing()) runtime.Value.initInt(args[1].toInt()) else runtime.Value.initInt(0);
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:3
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 3);
    reg_3.*.release(runtime.runtime_allocator);
    runtime.val_assign(reg_3, runtime.Value.initInt(reg_5.toInt()));
    __def_3 = true;
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:5
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 5);
    if (!__def_2) runtime.emitWarning("Undefined variable $a");
    reg_6.release(runtime.runtime_allocator);
    reg_6 = runtime.val_deref(reg_2).*;
    _ = reg_6.retain();
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:5
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 5);
    if (!__def_3) runtime.emitWarning("Undefined variable $b");
    reg_7.release(runtime.runtime_allocator);
    reg_7 = runtime.val_deref(reg_3).*;
    _ = reg_7.retain();
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:5
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 5);
    reg_8 = try runtime.php_add(reg_6, reg_7);

    // Cleanup: release allocated values (except return value)
    reg_1.*.release(runtime.runtime_allocator);
    reg_2.*.release(runtime.runtime_allocator);
    reg_3.*.release(runtime.runtime_allocator);
    return reg_8;
}

// MARKER: generateFunction called
pub fn @"__main__"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) !runtime.Value {
    _ = &ctx;
    const __prev_call_args = runtime.setCurrentCallArgs(args);
    defer runtime.restoreCurrentCallArgs(__prev_call_args);
    _ = allocator;
    _ = runtime;
    runtime.profiler.enterGlobal("__main__");
    defer runtime.profiler.exitGlobal("__main__");
    // Register declarations
    var reg_10: runtime.Value = runtime.Value.initNull();
    _ = &reg_10;
    var reg_12: runtime.Value = runtime.Value.initNull();
    _ = &reg_12;
    var reg_9: runtime.Value = runtime.Value.initNull();
    _ = &reg_9;
    var reg_2: runtime.Value = runtime.Value.initNull();
    _ = &reg_2;
    var reg_3: runtime.Value = runtime.Value.initNull();
    _ = &reg_3;
    var reg_1: runtime.Value = runtime.Value.initNull();
    _ = &reg_1;
    var reg_0: runtime.Value = runtime.Value.initNull();
    _ = &reg_0;
    var reg_4: runtime.Value = runtime.Value.initNull();
    _ = &reg_4;
    var reg_6: runtime.Value = runtime.Value.initNull();
    _ = &reg_6;
    var reg_5: runtime.Value = runtime.Value.initNull();
    _ = &reg_5;
    var reg_11: runtime.Value = runtime.Value.initNull();
    _ = &reg_11;
    var reg_7: runtime.Value = runtime.Value.initNull();
    _ = &reg_7;
    var reg_8: runtime.Value = runtime.Value.initNull();
    _ = &reg_8;

    var null_val = runtime.Value.initNull();
    _ = &null_val;

    // Instructions
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:9
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 9);
    reg_0.release(runtime.runtime_allocator);
    reg_0 = runtime.Value.initString(static_strings[5]);
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:9
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 9);
    _ = try runtime.php_echo(reg_0);
    if (runtime.hasException()) {
        @branchHint(.unlikely);
        // Cleanup on exception
        reg_1.release(runtime.runtime_allocator);
        reg_1 = runtime.Value.initNull();
        reg_4.release(runtime.runtime_allocator);
        reg_4 = runtime.Value.initNull();
        reg_10.release(runtime.runtime_allocator);
        reg_10 = runtime.Value.initNull();
        reg_12.release(runtime.runtime_allocator);
        reg_12 = runtime.Value.initNull();
        return error.RuntimeError;
    }
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:10
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 10);
    reg_1.release(runtime.runtime_allocator);
    reg_1 = try runtime.php_object_new_with_constructor("CallableClass", &[_]runtime.Value{}, runtime.runtime_allocator);
    if (runtime.hasException()) {
        @branchHint(.unlikely);
        // Cleanup on exception
        reg_4.release(runtime.runtime_allocator);
        reg_4 = runtime.Value.initNull();
        reg_10.release(runtime.runtime_allocator);
        reg_10 = runtime.Value.initNull();
        reg_12.release(runtime.runtime_allocator);
        reg_12 = runtime.Value.initNull();
        return error.RuntimeError;
    }
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:10
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 10);
    try setGlobalVar("$obj", reg_1);
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:11
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 11);
    reg_2.release(runtime.runtime_allocator);
    reg_2 = runtime.Value.initArray(try runtime.PHPArray.init(runtime.runtime_allocator));
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:11
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 11);
    reg_3.release(runtime.runtime_allocator);
    reg_3 = runtime.Value.initString(static_strings[11]);
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:11
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 11);
    reg_4.release(runtime.runtime_allocator);
    reg_4 = try runtime.php_create_closure(reg_3, reg_2, runtime.runtime_allocator);
    if (runtime.hasException()) {
        @branchHint(.unlikely);
        // Cleanup on exception
        reg_1.release(runtime.runtime_allocator);
        reg_1 = runtime.Value.initNull();
        reg_4.release(runtime.runtime_allocator);
        reg_4 = runtime.Value.initNull();
        reg_10.release(runtime.runtime_allocator);
        reg_10 = runtime.Value.initNull();
        reg_12.release(runtime.runtime_allocator);
        reg_12 = runtime.Value.initNull();
        return error.RuntimeError;
    }
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:11
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 11);
    try setGlobalVar("$add", reg_4);
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:12
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 12);
    reg_5.release(runtime.runtime_allocator);
    reg_5 = runtime.Value.initString(static_strings[9]);
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:12
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 12);
    reg_6.release(runtime.runtime_allocator);
    reg_6 = getGlobalVar("$add");
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:12
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 12);
    reg_7.release(runtime.runtime_allocator);
    reg_7 = runtime.Value.initInt(5);
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:12
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 12);
    reg_8.release(runtime.runtime_allocator);
    reg_8 = runtime.Value.initInt(3);
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:12
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 12);
    reg_9 = try runtime.php_invoke_callable(reg_6, &[_]runtime.Value{reg_7, reg_8}, runtime.runtime_allocator);
    if (runtime.hasException()) {
        @branchHint(.unlikely);
        // Cleanup on exception
        reg_1.release(runtime.runtime_allocator);
        reg_1 = runtime.Value.initNull();
        reg_4.release(runtime.runtime_allocator);
        reg_4 = runtime.Value.initNull();
        reg_10.release(runtime.runtime_allocator);
        reg_10 = runtime.Value.initNull();
        reg_12.release(runtime.runtime_allocator);
        reg_12 = runtime.Value.initNull();
        return error.RuntimeError;
    }
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:12
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 12);
    reg_10.release(runtime.runtime_allocator);
    reg_10 = try runtime.php_concat(reg_5, reg_9, runtime.runtime_allocator);
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:12
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 12);
    reg_11.release(runtime.runtime_allocator);
    reg_11 = runtime.Value.initString(static_strings[10]);
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:12
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 12);
    reg_12.release(runtime.runtime_allocator);
    reg_12 = try runtime.php_concat(reg_10, reg_11, runtime.runtime_allocator);
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:12
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 12);
    _ = try runtime.php_echo(reg_12);
    if (runtime.hasException()) {
        @branchHint(.unlikely);
        // Cleanup on exception
        reg_1.release(runtime.runtime_allocator);
        reg_1 = runtime.Value.initNull();
        reg_4.release(runtime.runtime_allocator);
        reg_4 = runtime.Value.initNull();
        reg_10.release(runtime.runtime_allocator);
        reg_10 = runtime.Value.initNull();
        reg_12.release(runtime.runtime_allocator);
        reg_12 = runtime.Value.initNull();
        return error.RuntimeError;
    }

    // Cleanup: release allocated values (except return value)
    if (!reg_1.isNull()) reg_1.release(runtime.runtime_allocator);
    if (!reg_4.isNull()) reg_4.release(runtime.runtime_allocator);
    if (!reg_10.isNull()) reg_10.release(runtime.runtime_allocator);
    if (!reg_12.isNull()) reg_12.release(runtime.runtime_allocator);
    return runtime.Value.initNull();
}

// MARKER: generateFunction called
pub fn @"__arrow_2"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) !runtime.Value {
    _ = &ctx;
    const __prev_call_args = runtime.setCurrentCallArgs(args);
    defer runtime.restoreCurrentCallArgs(__prev_call_args);
    _ = allocator;
    _ = runtime;
    runtime.profiler.enterGlobal("__arrow_2");
    defer runtime.profiler.exitGlobal("__arrow_2");
    // Register declarations
    var reg_1: runtime.Value = runtime.Value.initNull();
    _ = &reg_1;
    var reg_0: runtime.Value = runtime.Value.initNull();
    _ = &reg_0;
    var reg_2: runtime.Value = runtime.Value.initNull();
    _ = &reg_2;

    var null_val = runtime.Value.initNull();
    _ = &null_val;

    // Instructions
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:11
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 11);
    reg_0.release(runtime.runtime_allocator);
    reg_0 = getGlobalVar("$obj");
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:11
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 11);
    reg_1 = runtime.Value.initNull();
    // /Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php:11
    runtime.setSourceLocation("/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 11);
    reg_2.release(runtime.runtime_allocator);
    reg_2 = try runtime.php_object_call(reg_0, "add", &[_]runtime.Value{reg_1});
    if (runtime.hasException()) {
        @branchHint(.unlikely);
        return error.RuntimeError;
    }
    return reg_2;
}

pub fn @"select"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_select_builtin(ctx, args, allocator);
}

pub fn @"go"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_go(ctx, args, allocator);
}

pub fn @"go_wait_all"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_go_wait_all(ctx, args, allocator);
}

pub fn @"go_join"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_go_join(ctx, args, allocator);
}

pub fn @"get_class_methods"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_get_class_methods_builtin(ctx, args, allocator);
}

pub fn @"get_class_vars"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_get_class_vars_builtin(ctx, args, allocator);
}

pub fn @"get_object_vars"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_get_object_vars_builtin(ctx, args, allocator);
}

pub fn @"get_called_class"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_get_called_class_builtin(ctx, args, allocator);
}

pub fn @"forward_static_call"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_forward_static_call_builtin(ctx, args, allocator);
}

pub fn @"forward_static_call_array"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_forward_static_call_array_builtin(ctx, args, allocator);
}

fn registerAllClasses(allocator: std.mem.Allocator) !void {
    try runtime.ClassMeta.registerExceptionClass(allocator);
    const CallableClass_meta = try runtime.ClassMeta.init(allocator, "CallableClass");
    try CallableClass_meta.addMethod(.{ .name = "add", .func = @"CallableClass::add", .is_static = false, .is_public = true, .is_protected = false, .is_private = false, .param_count = 3, .required_params = 3 });
    if (CallableClass_meta.methods.get("__toString")) |m| CallableClass_meta.magic_toString = m.func;
    try runtime.registerClass(CallableClass_meta);
    if (CallableClass_meta.findMethod("__construct")) |m| { CallableClass_meta.magic_construct = m.func; }
    if (CallableClass_meta.findMethod("__destruct")) |m| { CallableClass_meta.magic_destruct = m.func; }
    if (CallableClass_meta.findMethod("__get")) |m| { CallableClass_meta.magic_get = m.func; }
    if (CallableClass_meta.findMethod("__set")) |m| { CallableClass_meta.magic_set = m.func; }
    if (CallableClass_meta.findMethod("__call")) |m| { CallableClass_meta.magic_call = m.func; }
    if (CallableClass_meta.findMethod("__callStatic")) |m| { CallableClass_meta.magic_callStatic = m.func; }
    if (CallableClass_meta.findMethod("__sleep")) |m| { CallableClass_meta.magic_sleep = m.func; }
    if (CallableClass_meta.findMethod("__wakeup")) |m| { CallableClass_meta.magic_wakeup = m.func; }
    if (CallableClass_meta.findMethod("__serialize")) |m| { CallableClass_meta.magic_serialize = m.func; }
    if (CallableClass_meta.findMethod("__unserialize")) |m| { CallableClass_meta.magic_unserialize = m.func; }
}

fn registerAllFunctions() !void {
    try runtime.registerUserFunctionWithLocation("__arrow_2", @"__arrow_2", "/Users/tuoke/Desktop/ai-zig-php-parser/zig-php-parser/fuzzy_scripts_27/pass/test_189_callable.php", 11);
    runtime.registerFunctionMeta("__arrow_2", 0, 0);
    runtime.registerFunctionMeta("__arrow_2", 0, 0);
    // 注册AOT callable hook
    runtime.aot_callable_hook = &aot_dispatch_callable;
}

// AOT变量函数dispatch：支持所有AOT注册的builtin函数
fn aot_dispatch_callable(name: []const u8, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    if (std.mem.eql(u8, name, "is_int")) {
        if (args.len > 0) return try runtime.php_is_int(args[0]);
        return runtime.Value.initNull();
    }
    if (std.mem.eql(u8, name, "is_dir")) {
        if (args.len > 0) return try runtime.php_is_dir(args[0]);
        return runtime.Value.initNull();
    }
    if (std.mem.eql(u8, name, "is_dir")) {
        if (args.len > 0) return try runtime.php_is_dir(args[0]);
        return runtime.Value.initNull();
    }
    if (std.mem.eql(u8, name, "is_nan")) {
        if (args.len > 0) return try runtime.php_is_nan(args[0]);
        return runtime.Value.initNull();
    }
    if (std.mem.eql(u8, name, "is_bool")) {
        if (args.len > 0) return try runtime.php_is_bool(args[0]);
        return runtime.Value.initNull();
    }
    if (std.mem.eql(u8, name, "is_file")) {
        if (args.len > 0) return try runtime.php_is_file(args[0]);
        return runtime.Value.initNull();
    }
    if (std.mem.eql(u8, name, "is_file")) {
        if (args.len > 0) return try runtime.php_is_file(args[0]);
        return runtime.Value.initNull();
    }
    if (std.mem.eql(u8, name, "is_null")) {
        if (args.len > 0) return try runtime.php_is_null(args[0]);
        return runtime.Value.initNull();
    }
    if (std.mem.eql(u8, name, "is_array")) {
        if (args.len > 0) return try runtime.php_is_array(args[0]);
        return runtime.Value.initNull();
    }
    if (std.mem.eql(u8, name, "is_float")) {
        if (args.len > 0) return try runtime.php_is_float(args[0]);
        return runtime.Value.initNull();
    }
    if (std.mem.eql(u8, name, "is_string")) {
        if (args.len > 0) return try runtime.php_is_string(args[0]);
        return runtime.Value.initNull();
    }
    if (std.mem.eql(u8, name, "is_scalar")) {
        if (args.len > 0) return try runtime.php_is_scalar(args[0]);
        return runtime.Value.initNull();
    }
    if (std.mem.eql(u8, name, "is_finite")) {
        if (args.len > 0) return try runtime.php_is_finite(args[0]);
        return runtime.Value.initNull();
    }
    if (std.mem.eql(u8, name, "is_object")) {
        if (args.len > 0) return try runtime.php_is_object(args[0]);
        return runtime.Value.initNull();
    }
    if (std.mem.eql(u8, name, "is_numeric")) {
        if (args.len > 0) return try runtime.php_is_numeric(args[0]);
        return runtime.Value.initNull();
    }
    if (std.mem.eql(u8, name, "is_resource")) {
        if (args.len > 0) return try runtime.php_is_resource(args[0]);
        return runtime.Value.initNull();
    }
    if (std.mem.eql(u8, name, "is_resource")) {
        if (args.len > 0) return try runtime.php_is_resource(args[0]);
        return runtime.Value.initNull();
    }
    if (std.mem.eql(u8, name, "is_infinite")) {
        if (args.len > 0) return try runtime.php_is_infinite(args[0]);
        return runtime.Value.initNull();
    }
    if (std.mem.eql(u8, name, "is_readable")) {
        if (args.len > 0) return try runtime.php_is_readable(args[0]);
        return runtime.Value.initNull();
    }
    if (std.mem.eql(u8, name, "is_writable")) {
        if (args.len > 0) return try runtime.php_is_writable(args[0]);
        return runtime.Value.initNull();
    }
    if (std.mem.eql(u8, name, "is_callable")) {
        if (args.len > 0) return try runtime.php_is_callable(args[0]);
        return runtime.Value.initNull();
    }
    if (std.mem.eql(u8, name, "is_iterable")) {
        if (args.len > 0) return try runtime.php_is_iterable(args[0]);
        return runtime.Value.initNull();
    }
    if (std.mem.eql(u8, name, "is_countable")) {
        if (args.len > 0) return try runtime.php_is_countable(args[0]);
        return runtime.Value.initNull();
    }
    if (std.mem.eql(u8, name, "is_subclass_of")) {
        if (args.len >= 2) return try runtime.php_is_subclass_of(args[0], args[1]);
        return runtime.Value.initNull();
    }
    _ = allocator;
    return error.UnknownFunction;
}

// AOT已注册函数名列表（用于function_exists）
const aot_registered_functions = std.StaticStringMap(void).initComptime(.{
    .{ "go", {} },
    .{ "pi", {} },
    .{ "sin", {} },
    .{ "chr", {} },
    .{ "md5", {} },
    .{ "cos", {} },
    .{ "abs", {} },
    .{ "tan", {} },
    .{ "log", {} },
    .{ "pow", {} },
    .{ "die", {} },
    .{ "key", {} },
    .{ "exp", {} },
    .{ "end", {} },
    .{ "ord", {} },
    .{ "min", {} },
    .{ "max", {} },
    .{ "ftok", {} },
    .{ "sort", {} },
    .{ "date", {} },
    .{ "join", {} },
    .{ "time", {} },
    .{ "next", {} },
    .{ "ceil", {} },
    .{ "atan", {} },
    .{ "rand", {} },
    .{ "prev", {} },
    .{ "fmod", {} },
    .{ "exit", {} },
    .{ "exec", {} },
    .{ "echo", {} },
    .{ "copy", {} },
    .{ "each", {} },
    .{ "sha1", {} },
    .{ "file", {} },
    .{ "acos", {} },
    .{ "asin", {} },
    .{ "trim", {} },
    .{ "sqrt", {} },
    .{ "ksort", {} },
    .{ "rtrim", {} },
    .{ "isset", {} },
    .{ "print", {} },
    .{ "fread", {} },
    .{ "nl2br", {} },
    .{ "floor", {} },
    .{ "fopen", {} },
    .{ "round", {} },
    .{ "empty", {} },
    .{ "unset", {} },
    .{ "atan2", {} },
    .{ "rsort", {} },
    .{ "fgets", {} },
    .{ "fseek", {} },
    .{ "log10", {} },
    .{ "reset", {} },
    .{ "range", {} },
    .{ "count", {} },
    .{ "asort", {} },
    .{ "mkdir", {} },
    .{ "hypot", {} },
    .{ "srand", {} },
    .{ "sleep", {} },
    .{ "usort", {} },
    .{ "rmdir", {} },
    .{ "ltrim", {} },
    .{ "rename", {} },
    .{ "unlink", {} },
    .{ "fclose", {} },
    .{ "strpos", {} },
    .{ "uasort", {} },
    .{ "uksort", {} },
    .{ "mktime", {} },
    .{ "strstr", {} },
    .{ "krsort", {} },
    .{ "strrev", {} },
    .{ "substr", {} },
    .{ "usleep", {} },
    .{ "strlen", {} },
    .{ "strval", {} },
    .{ "arsort", {} },
    .{ "is_int", {} },
    .{ "strchr", {} },
    .{ "system", {} },
    .{ "intval", {} },
    .{ "is_dir", {} },
    .{ "sscanf", {} },
    .{ "uniqid", {} },
    .{ "define", {} },
    .{ "is_dir", {} },
    .{ "decbin", {} },
    .{ "is_nan", {} },
    .{ "fwrite", {} },
    .{ "unlink", {} },
    .{ "printf", {} },
    .{ "strcmp", {} },
    .{ "sizeof", {} },
    .{ "getcwd", {} },
    .{ "mt_rand", {} },
    .{ "deg2rad", {} },
    .{ "sprintf", {} },
    .{ "strrpos", {} },
    .{ "is_bool", {} },
    .{ "stripos", {} },
    .{ "print_r", {} },
    .{ "defined", {} },
    .{ "sem_get", {} },
    .{ "current", {} },
    .{ "dirname", {} },
    .{ "hex2bin", {} },
    .{ "boolval", {} },
    .{ "gettype", {} },
    .{ "is_file", {} },
    .{ "implode", {} },
    .{ "str_pad", {} },
    .{ "is_file", {} },
    .{ "natsort", {} },
    .{ "bin2hex", {} },
    .{ "explode", {} },
    .{ "is_null", {} },
    .{ "scandir", {} },
    .{ "extract", {} },
    .{ "ucwords", {} },
    .{ "lcfirst", {} },
    .{ "ucfirst", {} },
    .{ "compact", {} },
    .{ "settype", {} },
    .{ "shuffle", {} },
    .{ "ini_get", {} },
    .{ "rad2deg", {} },
    .{ "is_array", {} },
    .{ "mt_srand", {} },
    .{ "in_array", {} },
    .{ "basename", {} },
    .{ "strripos", {} },
    .{ "is_float", {} },
    .{ "floatval", {} },
    .{ "filesize", {} },
    .{ "filesize", {} },
    .{ "wordwrap", {} },
    .{ "var_dump", {} },
    .{ "array_pad", {} },
    .{ "is_string", {} },
    .{ "str_split", {} },
    .{ "array_map", {} },
    .{ "serialize", {} },
    .{ "php_uname", {} },
    .{ "php_deref", {} },
    .{ "array_pad", {} },
    .{ "array_sum", {} },
    .{ "array_pop", {} },
    .{ "strtotime", {} },
    .{ "is_scalar", {} },
    .{ "microtime", {} },
    .{ "get_class", {} },
    .{ "getrusage", {} },
    .{ "is_finite", {} },
    .{ "preg_grep", {} },
    .{ "urlencode", {} },
    .{ "gc_enable", {} },
    .{ "urldecode", {} },
    .{ "is_object", {} },
    .{ "str_repeat", {} },
    .{ "strcasecmp", {} },
    .{ "strtoupper", {} },
    .{ "array_rand", {} },
    .{ "shmop_open", {} },
    .{ "array_walk", {} },
    .{ "php_concat", {} },
    .{ "array_flip", {} },
    .{ "array_diff", {} },
    .{ "preg_split", {} },
    .{ "array_rand", {} },
    .{ "array_fill", {} },
    .{ "array_keys", {} },
    .{ "is_numeric", {} },
    .{ "preg_split", {} },
    .{ "array_fill", {} },
    .{ "sem_remove", {} },
    .{ "strtolower", {} },
    .{ "posix_kill", {} },
    .{ "array_walk", {} },
    .{ "pcntl_wait", {} },
    .{ "array_flip", {} },
    .{ "array_push", {} },
    .{ "filter_var", {} },
    .{ "preg_match", {} },
    .{ "array_diff", {} },
    .{ "var_export", {} },
    .{ "strip_tags", {} },
    .{ "pcntl_fork", {} },
    .{ "str_getcsv", {} },
    .{ "shell_exec", {} },
    .{ "random_int", {} },
    .{ "preg_match", {} },
    .{ "is_resource", {} },
    .{ "json_decode", {} },
    .{ "json_encode", {} },
    .{ "unserialize", {} },
    .{ "chunk_split", {} },
    .{ "is_resource", {} },
    .{ "is_infinite", {} },
    .{ "is_readable", {} },
    .{ "is_writable", {} },
    .{ "pcntl_alarm", {} },
    .{ "file_exists", {} },
    .{ "file_exists", {} },
    .{ "array_slice", {} },
    .{ "is_callable", {} },
    .{ "str_replace", {} },
    .{ "shmop_close", {} },
    .{ "array_chunk", {} },
    .{ "array_shift", {} },
    .{ "is_iterable", {} },
    .{ "array_merge", {} },
    .{ "preg_replace", {} },
    .{ "getStaticVar", {} },
    .{ "socket_close", {} },
    .{ "class_exists", {} },
    .{ "rawurlencode", {} },
    .{ "rawurldecode", {} },
    .{ "trait_exists", {} },
    .{ "array_splice", {} },
    .{ "posix_mkfifo", {} },
    .{ "array_column", {} },
    .{ "is_countable", {} },
    .{ "posix_getpid", {} },
    .{ "pcntl_signal", {} },
    .{ "array_values", {} },
    .{ "array_splice", {} },
    .{ "func_get_arg", {} },
    .{ "setStaticVar", {} },
    .{ "random_bytes", {} },
    .{ "str_ireplace", {} },
    .{ "str_contains", {} },
    .{ "preg_replace", {} },
    .{ "htmlentities", {} },
    .{ "array_unique", {} },
    .{ "array_filter", {} },
    .{ "array_search", {} },
    .{ "array_reduce", {} },
    .{ "array_column", {} },
    .{ "array_product", {} },
    .{ "array_reverse", {} },
    .{ "str_ends_with", {} },
    .{ "php_sapi_name", {} },
    .{ "array_combine", {} },
    .{ "func_num_args", {} },
    .{ "func_get_args", {} },
    .{ "array_unshift", {} },
    .{ "pcntl_waitpid", {} },
    .{ "array_is_list", {} },
    .{ "method_exists", {} },
    .{ "array_combine", {} },
    .{ "msg_get_queue", {} },
    .{ "base64_decode", {} },
    .{ "base64_encode", {} },
    .{ "number_format", {} },
    .{ "preg_match_all", {} },
    .{ "substr_replace", {} },
    .{ "php_go_builtin", {} },
    .{ "throwThrowable", {} },
    .{ "is_subclass_of", {} },
    .{ "array_diff_key", {} },
    .{ "preg_match_all", {} },
    .{ "array_key_last", {} },
    .{ "str_word_count", {} },
    .{ "escapeshellarg", {} },
    .{ "php_object_new", {} },
    .{ "array_key_last", {} },
    .{ "php_ref_assign", {} },
    .{ "escapeshellcmd", {} },
    .{ "array_intersect", {} },
    .{ "array_intersect", {} },
    .{ "function_exists", {} },
    .{ "php_json_encode", {} },
    .{ "array_key_first", {} },
    .{ "property_exists", {} },
    .{ "array_fill_keys", {} },
    .{ "array_multisort", {} },
    .{ "array_fill_keys", {} },
    .{ "array_key_first", {} },
    .{ "array_multisort", {} },
    .{ "str_starts_with", {} },
    .{ "memory_get_usage", {} },
    .{ "interface_exists", {} },
    .{ "php_constant_get", {} },
    .{ "msg_remove_queue", {} },
    .{ "array_key_exists", {} },
    .{ "get_parent_class", {} },
    .{ "sys_get_temp_dir", {} },
    .{ "htmlspecialchars", {} },
    .{ "php_object_unset", {} },
    .{ "gc_collect_cycles", {} },
    .{ "file_put_contents", {} },
    .{ "file_get_contents", {} },
    .{ "pcntl_sigprocmask", {} },
    .{ "file_put_contents", {} },
    .{ "pcntl_wexitstatus", {} },
    .{ "file_get_contents", {} },
    .{ "array_count_values", {} },
    .{ "php_create_closure", {} },
    .{ "array_count_values", {} },
    .{ "socket_create_pair", {} },
    .{ "php_ref_assign_ptr", {} },
    .{ "php_array_iter_key", {} },
    .{ "php_array_iter_free", {} },
    .{ "php_array_iter_init", {} },
    .{ "json_last_error_msg", {} },
    .{ "array_walk_recursive", {} },
    .{ "php_array_merge_into", {} },
    .{ "array_walk_recursive", {} },
    .{ "memory_get_peak_usage", {} },
    .{ "preg_replace_callback", {} },
    .{ "preg_replace_callback", {} },
    .{ "pcntl_signal_dispatch", {} },
    .{ "php_args_append_spread", {} },
    .{ "php_array_iter_next_ref", {} },
    .{ "php_array_iter_init_ref", {} },
    .{ "preg_match_with_matches", {} },
    .{ "htmlspecialchars_decode", {} },
    .{ "php_array_iter_free_ref", {} },
    .{ "php_array_iter_valid_ref", {} },
    .{ "php_invoke_callable_args_array", {} },
    .{ "php_array_iter_value_ref_reuse", {} },
    .{ "php_object_new_with_constructor", {} },
    .{ "php_object_call_safe_args_array", {} },
});

pub fn aot_function_exists(name: []const u8) runtime.Value {
    if (aot_registered_functions.has(name)) return runtime.Value.initBool(true);
    if (runtime.user_function_registry) |reg| {
        if (reg.contains(name)) return runtime.Value.initBool(true);
    }
    return runtime.Value.initBool(false);
}

// AOT变量函数调用：覆盖runtime的invoke_callable，支持AOT注册函数
pub fn aot_call_named_function(name: []const u8, args: []const runtime.Value, allocator: std.mem.Allocator) !runtime.Value {
    _ = allocator;
    _ = args;
    _ = name;
    return error.UnknownFunction;
}

// 全局变量表
var global_vars: std.StringHashMap(runtime.Value) = undefined;
var global_vars_initialized: bool = false;

// 全局变量引用绑定表: target -> source (e.g., $b = &$a means $b -> $a)
var global_ref_bindings: std.StringHashMap([]const u8) = undefined;
var global_ref_bindings_initialized: bool = false;

// 创建全局变量引用绑定: $target = &$source
pub fn bindGlobalRef(target: []const u8, source: []const u8) !void {
    if (!global_ref_bindings_initialized) {
        global_ref_bindings = std.StringHashMap([]const u8).init(runtime.runtime_allocator);
        global_ref_bindings_initialized = true;
    }
    // 解析 source 的引用链，找到真正的源变量
    const resolved_source = resolveRefSource(source);
    // 复制 target 和 resolved_source 字符串
    const target_copy = try runtime.runtime_allocator.dupe(u8, target);
    const source_copy = try runtime.runtime_allocator.dupe(u8, resolved_source);
    // 如果已存在旧绑定，释放旧的字符串
    if (try global_ref_bindings.fetchPut(target_copy, source_copy)) |old| {
        runtime.runtime_allocator.free(old.key);
        runtime.runtime_allocator.free(old.value);
    }
    // 同步当前值: $target 应该和 resolved_source 指向相同的值
    if (global_vars_initialized) {
        if (global_vars.get(resolved_source)) |src_val| {
            const gop = try global_vars.getOrPut(target);
            if (!gop.found_existing) {
                gop.key_ptr.* = try runtime.runtime_allocator.dupe(u8, target);
            }
            if (gop.found_existing) {
                gop.value_ptr.release(runtime.runtime_allocator);
            }
            _ = src_val.retain();
            gop.value_ptr.* = src_val;
        }
    }
}

// 获取变量的引用源（如果是引用则返回源变量名，否则返回自身）
fn resolveRefSource(name: []const u8) []const u8 {
    if (!global_ref_bindings_initialized) return name;
    // 循环解析引用链
    var current = name;
    var depth: usize = 0;
    while (depth < 10) : (depth += 1) {
        if (global_ref_bindings.get(current)) |source| {
            current = source;
        } else {
            break;
        }
    }
    return current;
}

// 查找所有引用同一源的变量
fn findAllRefsToSource(source: []const u8, out_buf: *[32][]const u8) usize {
    if (!global_ref_bindings_initialized) return 0;
    var count: usize = 0;
    var it = global_ref_bindings.iterator();
    while (it.next()) |entry| {
        if (count >= 32) break;
        const resolved = resolveRefSource(entry.key_ptr.*);
        if (std.mem.eql(u8, resolved, source)) {
            out_buf[count] = entry.key_ptr.*;
            count += 1;
        }
    }
    return count;
}

pub fn getGlobalVar(name: []const u8) runtime.Value {
    // 超全局变量直接从global_vars读取
    if (name.len > 1 and name[0] == '$' and name[1] == '_' and global_vars_initialized) {
        if (global_vars.get(name)) |value| {
            _ = value.retain();
            return value;
        }
    }
    if (std.mem.eql(u8, name, "$GLOBALS") and global_vars_initialized) {
        if (global_vars.get(name)) |value| {
            _ = value.retain();
            return value;
        }
    }
    // 先查找常量表
    if (runtime.constants.get(name)) |const_val| {
        _ = const_val.retain();
        return const_val;
    }
    // 再查找全局变量表
    if (!global_vars_initialized) {
        var wbuf: [256]u8 = undefined;
        const wmsg = std.fmt.bufPrint(&wbuf, "Undefined variable {s}", .{name}) catch "Undefined variable";
        runtime.emitWarning(wmsg);
        return runtime.Value.initNull();
    }
    if (global_vars.get(name)) |value| {
        _ = value.retain();
        return value;
    }
    var wbuf2: [256]u8 = undefined;
    const wmsg2 = std.fmt.bufPrint(&wbuf2, "Undefined variable {s}", .{name}) catch "Undefined variable";
    runtime.emitWarning(wmsg2);
    return runtime.Value.initNull();
}

pub fn getGlobalVarNoWarn(name: []const u8) runtime.Value {
    if (name.len > 1 and name[0] == '$' and name[1] == '_' and global_vars_initialized) {
        if (global_vars.get(name)) |value| {
            _ = value.retain();
            return value;
        }
    }
    if (std.mem.eql(u8, name, "$GLOBALS") and global_vars_initialized) {
        if (global_vars.get(name)) |value| {
            _ = value.retain();
            return value;
        }
    }
    if (runtime.constants.get(name)) |const_val| {
        _ = const_val.retain();
        return const_val;
    }
    if (!global_vars_initialized) return runtime.Value.initNull();
    if (global_vars.get(name)) |value| {
        _ = value.retain();
        return value;
    }
    return runtime.Value.initNull();
}

pub fn globalVarIsDefined(name: []const u8) bool {
    if (runtime.constants.get(name) != null) return true;
    if (!global_vars_initialized) return false;
    return global_vars.get(name) != null;
}

pub fn setGlobalVar(name: []const u8, value: runtime.Value) !void {
    if (!global_vars_initialized) return;
    
    // 解析引用链：找到真正的源变量
    const source = resolveRefSource(name);
    
    // 设置源变量的值
    try setGlobalVarDirect(source, value);
    
    // 如果设置的是引用变量，也同步更新源变量
    if (!std.mem.eql(u8, name, source)) {
        try setGlobalVarDirect(name, value);
    }
    
    // 查找所有引用同一源的其他变量并同步更新
    var refs_buf: [32][]const u8 = undefined;
    const ref_count = findAllRefsToSource(source, &refs_buf);
    for (refs_buf[0..ref_count]) |ref_name| {
        if (!std.mem.eql(u8, ref_name, name)) {
            try setGlobalVarDirect(ref_name, value);
        }
    }
}

// 直接设置全局变量值，不处理引用传播
fn setGlobalVarDirect(name: []const u8, value: runtime.Value) !void {
    if (!global_vars_initialized) return;
    const gop = try global_vars.getOrPut(name);
    if (!gop.found_existing) {
        const key_copy = try runtime.runtime_allocator.dupe(u8, name);
        gop.key_ptr.* = key_copy;
        _ = value.retain();
        gop.value_ptr.* = value;
    } else {
        gop.value_ptr.release(runtime.runtime_allocator);
        _ = value.retain();
        gop.value_ptr.* = value;
    }
}

pub fn unsetGlobalVar(name_val: runtime.Value) !void {
    if (!global_vars_initialized) return;
    if (!name_val.isString()) return;
    const name = name_val.asString().data;
    // 从全局变量表中删除并释放
    if (global_vars.getPtr(name)) |val_ptr| {
        // 通知弱引用系统：对象即将被 unset
        runtime.php_weak_mark_dead(val_ptr.*);
        // Release setGlobalVar的retain
        val_ptr.release(runtime.runtime_allocator);
        // 从表中删除
        if (global_vars.fetchRemove(name)) |kv| {
            runtime.runtime_allocator.free(kv.key);
        }
    }
}

pub fn getGlobalVarDynamic(name_val: runtime.Value) !runtime.Value {
    const name_str = try name_val.toString(runtime.runtime_allocator);
    defer name_str.release(runtime.runtime_allocator);
    return getGlobalVar(name_str.data);
}

pub fn setGlobalVarDynamic(name_val: runtime.Value, value: runtime.Value) !void {
    const name_str = try name_val.toString(runtime.runtime_allocator);
    defer name_str.release(runtime.runtime_allocator);
    // Add $ prefix if not present
    if (name_str.data.len > 0 and name_str.data[0] == '$') {
        try setGlobalVar(name_str.data, value);
    } else {
        const prefixed = try std.fmt.allocPrint(runtime.runtime_allocator, "${s}", .{name_str.data});
        defer runtime.runtime_allocator.free(prefixed);
        try setGlobalVar(prefixed, value);
    }
}

pub fn main() !void {
    const allocator = std.heap.page_allocator;

    runtime.initRuntime(allocator);
    defer runtime.deinitRuntime();

    // 初始化全局变量表
    global_vars = std.StringHashMap(runtime.Value).init(allocator);
    global_vars_initialized = true;

    // 初始化超全局变量
    {
        const superglobal_names = [_][]const u8{ "$_GET", "$_POST", "$_REQUEST", "$_COOKIE", "$_SESSION", "$_ENV", "$_FILES", "$GLOBALS" };
        for (superglobal_names) |name| {
            const key = try allocator.dupe(u8, name);
            const arr = try runtime.PHPArray.init(allocator);
            try global_vars.put(key, runtime.Value.initArray(arr));
        }
        // $_SERVER with basic info
        const server_key = try allocator.dupe(u8, "$_SERVER");
        const server_arr = try runtime.PHPArray.init(allocator);
        const argv_arr = try runtime.PHPArray.init(allocator);
        for (std.os.argv, 0..) |arg_ptr, i| {
            const arg = std.mem.span(arg_ptr);
            const arg_str = try runtime.PHPString.init(allocator, arg);
            try argv_arr.push(allocator, runtime.Value.initString(arg_str));
            if (i == 0) {
                const script_str = try runtime.PHPString.init(allocator, "SCRIPT_FILENAME");
                try server_arr.setByValue(allocator, runtime.Value.initString(script_str), runtime.Value.initString(arg_str));
            }
        }
        const argc_str = try runtime.PHPString.init(allocator, "argc");
        try server_arr.setByValue(allocator, runtime.Value.initString(argc_str), runtime.Value.initInt(@intCast(std.os.argv.len)));
        const argv_str = try runtime.PHPString.init(allocator, "argv");
        try server_arr.setByValue(allocator, runtime.Value.initString(argv_str), runtime.Value.initArray(argv_arr));
        const sapi_str = try runtime.PHPString.init(allocator, "PHP_SAPI");
        const sapi_val = try runtime.PHPString.init(allocator, "cli");
        try server_arr.setByValue(allocator, runtime.Value.initString(sapi_str), runtime.Value.initString(sapi_val));
        try global_vars.put(server_key, runtime.Value.initArray(server_arr));
    }

    // 注意：cleanupAllClasses 必须在 global_vars 清理之后执行
    // 因为 global_vars 中的对象可能需要调用 __destruct，
    // 而 __destruct 依赖 class_registry（由 cleanupAllClasses 清除）
    // Zig defer 是 LIFO 顺序，所以先注册 cleanupAllClasses，
    // 再注册 global_vars cleanup，这样 global_vars cleanup 先执行
    defer runtime.cleanupAllClasses();
    defer {
        var it = global_vars.valueIterator();
        while (it.next()) |val| {
            val.release(runtime.runtime_allocator);
        }
        global_vars.deinit();
    }
    // 初始化静态字符串池（一次性开销）
    initStaticStrings();
    // 初始化PHP预定义常量
    {
        const key1 = try allocator.dupeZ(u8, "COUNT_RECURSIVE");
        try runtime.constants.put(key1, runtime.Value.initInt(1));
        const key2 = try allocator.dupeZ(u8, "COUNT_NORMAL");
        try runtime.constants.put(key2, runtime.Value.initInt(0));
    }
    var alloc_stats_enabled: bool = false;
    if (std.process.getEnvVarOwned(allocator, "ZIGPHP_ALLOC_STATS")) |v| {
        alloc_stats_enabled = true;
        allocator.free(v);
    } else |_| {}

    defer if (alloc_stats_enabled) {
        const s = runtime.getAllocStats();
        std.debug.print(
            "ALLOC_STATS alloc_bytes={d} alloc_count={d} free_bytes={d} free_count={d} live_bytes={d} live_allocs={d} peak_live_bytes={d} peak_live_allocs={d} php_string_live_objects={d} php_string_live_bytes={d} php_array_live_objects={d} php_object_live_objects={d}\\n",
            .{ s.alloc_bytes, s.alloc_count, s.free_bytes, s.free_count, s.live_bytes, s.live_allocs, s.peak_live_bytes, s.peak_live_allocs, s.php_string_live_objects, s.php_string_live_bytes, s.php_array_live_objects, s.php_object_live_objects },
        );
    };

    var profiling_enabled: bool = false;
    if (std.process.getEnvVarOwned(allocator, "ZIGPHP_PROFILE")) |v| {
        profiling_enabled = true;
        allocator.free(v);
    } else |_| {}

    var profiler: runtime.profiler.Profiler = undefined;
    var generator: runtime.flamegraph.FlameGraphGenerator = undefined;

    if (profiling_enabled) {
        profiler = try runtime.profiler.Profiler.init(allocator, .custom);
        profiler.enable();
        runtime.profiler.setGlobalProfiler(&profiler);

        generator = try runtime.flamegraph.FlameGraphGenerator.init(allocator, &profiler);
        generator.setMinDisplayTime(0);
        if (std.process.getEnvVarOwned(allocator, "ZIGPHP_PROFILE_INTERVAL_NS")) |s| {
            defer allocator.free(s);
            generator.setSamplingInterval(std.fmt.parseInt(u64, s, 10) catch generator.sampling_interval_ns);
        } else |_| {}
        try generator.startSampling();
    }

    defer if (profiling_enabled) {
        generator.stopSampling();

        const folded = generator.generateFoldedFormat(allocator) catch null;
        if (folded) |data| {
            defer allocator.free(data);
            const out = std.fs.cwd().createFile("flamegraph.txt", .{}) catch null;
            if (out) |file| {
                defer file.close();
                _ = file.writeAll(data) catch {};
            }
        }

        const pb = std.fs.cwd().createFile("profile.pb", .{}) catch null;
        if (pb) |file| {
            defer file.close();
            var buf: [16 * 1024]u8 = undefined;
            var w = file.writer(&buf);
            runtime.pprof.writeCpuProfileFromFlameGraph(allocator, &w.interface, generator.root, generator.sampling_interval_ns) catch {};
            _ = w.end() catch {};
        }

        generator.deinit();
        runtime.profiler.setGlobalProfiler(null);
        profiler.deinit();
    };

    // 注册所有类
    registerAllClasses(allocator) catch {};
    // 注册所有函数
    registerAllFunctions() catch {};

    _ = @"__main__"(runtime.Value.initNull(), &[_]runtime.Value{}, allocator) catch |err| {
        if (runtime.hasException()) {
            runtime.php_handle_uncaught_exception();
            return;
        }
        return err;
    };
    _ = runtime.php_go_wait_all(runtime.Value.initNull(), &[_]runtime.Value{}, allocator) catch {};
}
