// Generated by zig-php AOT compiler
// DO NOT EDIT

const std = @import("std");
const runtime = @import("runtime_lib.zig");

// String table
const string_table = [_][]const u8{
    "$arr",
    "$cnt",
    "count",
    "$sum",
    "$v",
    "UnsetCnt: ",
    ",",
    " (expect 3,8)\n",
};

// 静态字符串池（运行时初始化一次）
var static_strings: [string_table.len]*runtime.PHPString = undefined;
var static_strings_initialized = false;

fn initStaticStrings() void {
    if (static_strings_initialized) return;
    for (string_table, 0..) |str, i| {
        static_strings[i] = runtime.PHPString.initStatic(str);
    }
    static_strings_initialized = true;
}


// MARKER: generateFunction called
pub fn @"__main__"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) !runtime.Value {
    _ = &ctx;
    _ = &args;
    _ = allocator;
    _ = runtime;
    runtime.profiler.enterGlobal("__main__");
    defer runtime.profiler.exitGlobal("__main__");
    // Register declarations
    var reg_20: i64 = 0;
    _ = &reg_20;
    var reg_12: runtime.Value = runtime.Value.initNull();
    _ = &reg_12;
    var reg_21: i64 = 0;
    _ = &reg_21;
    var reg_35: i64 = 0;
    _ = &reg_35;
    var reg_32: runtime.Value = runtime.Value.initNull();
    _ = &reg_32;
    var reg_9: i64 = 0;
    _ = &reg_9;
    var reg_19: runtime.Value = runtime.Value.initNull();
    _ = &reg_19;
    var reg_2: i64 = 0;
    _ = &reg_2;
    var reg_3: i64 = 0;
    _ = &reg_3;
    var reg_27: runtime.Value = runtime.Value.initNull();
    _ = &reg_27;
    var reg_1: i64 = 0;
    _ = &reg_1;
    var reg_22: i64 = 0;
    _ = &reg_22;
    var reg_25: runtime.Value = runtime.Value.initNull();
    _ = &reg_25;
    var reg_15: runtime.Value = runtime.Value.initNull();
    _ = &reg_15;
    var reg_13: runtime.Value = runtime.Value.initNull();
    _ = &reg_13;
    var reg_11: runtime.Value = runtime.Value.initNull();
    _ = &reg_11;
    var reg_37: runtime.Value = runtime.Value.initNull();
    _ = &reg_37;
    var reg_7: runtime.Value = runtime.Value.initNull();
    _ = &reg_7;
    var reg_8: runtime.Value = runtime.Value.initNull();
    _ = &reg_8;
    var reg_10: runtime.Value = runtime.Value.initNull();
    _ = &reg_10;
    var reg_34: runtime.Value = runtime.Value.initNull();
    _ = &reg_34;
    var reg_26: runtime.Value = runtime.Value.initNull();
    _ = &reg_26;
    var reg_17: runtime.Value = runtime.Value.initNull();
    _ = &reg_17;
    var reg_14: runtime.Value = runtime.Value.initNull();
    _ = &reg_14;
    var reg_30: runtime.Value = runtime.Value.initNull();
    _ = &reg_30;
    var reg_31: i64 = 0;
    _ = &reg_31;
    var reg_23: runtime.Value = runtime.Value.initNull();
    _ = &reg_23;
    var reg_0: runtime.Value = runtime.Value.initNull();
    _ = &reg_0;
    var reg_18: runtime.Value = runtime.Value.initNull();
    _ = &reg_18;
    var reg_4: i64 = 0;
    _ = &reg_4;
    var reg_6: runtime.Value = runtime.Value.initNull();
    _ = &reg_6;
    var reg_33: runtime.Value = runtime.Value.initNull();
    _ = &reg_33;
    var reg_29: runtime.Value = runtime.Value.initNull();
    _ = &reg_29;
    var reg_16: bool = false;
    _ = &reg_16;
    var reg_5: runtime.Value = runtime.Value.initNull();
    _ = &reg_5;
    var reg_24: runtime.Value = runtime.Value.initNull();
    _ = &reg_24;
    var reg_28: runtime.Value = runtime.Value.initNull();
    _ = &reg_28;
    var reg_36: i64 = 0;
    _ = &reg_36;

    // Block 0: entry
            // test_unset_count_loop.php:2
    // test_unset_count_loop.php:2
            // test_unset_count_loop.php:4
    // test_unset_count_loop.php:4
            // test_unset_count_loop.php:5
    // test_unset_count_loop.php:5
            // test_unset_count_loop.php:6
    // test_unset_count_loop.php:6
            // test_unset_count_loop.php:2
        reg_0 = runtime.Value.initArray(try runtime.PHPArray.init(runtime.runtime_allocator));
            // test_unset_count_loop.php:2
        reg_1 = 1;
            // test_unset_count_loop.php:2
        try reg_0.asArray().push(runtime.runtime_allocator, runtime.Value.initInt(reg_1));
            // test_unset_count_loop.php:2
        reg_2 = 2;
            // test_unset_count_loop.php:2
        try reg_0.asArray().push(runtime.runtime_allocator, runtime.Value.initInt(reg_2));
            // test_unset_count_loop.php:2
        reg_3 = 3;
            // test_unset_count_loop.php:2
        try reg_0.asArray().push(runtime.runtime_allocator, runtime.Value.initInt(reg_3));
            // test_unset_count_loop.php:2
        reg_4 = 4;
            // test_unset_count_loop.php:2
        try reg_0.asArray().push(runtime.runtime_allocator, runtime.Value.initInt(reg_4));
            // test_unset_count_loop.php:2
    // test_unset_count_loop.php:2
            // test_unset_count_loop.php:4
        reg_6 = reg_0;
            // test_unset_count_loop.php:4
        reg_7 = try runtime.php_count(reg_0);
            // test_unset_count_loop.php:4
    // test_unset_count_loop.php:4
            // test_unset_count_loop.php:5
        reg_9 = 0;
            // test_unset_count_loop.php:5
    // test_unset_count_loop.php:5
            // test_unset_count_loop.php:6
        reg_11 = reg_0;
            // test_unset_count_loop.php:6
        reg_12 = try runtime.php_array_iter_init(reg_0, runtime.runtime_allocator);
            // test_unset_count_loop.php:6
    // test_unset_count_loop.php:6
            // test_unset_count_loop.php:6
    // test_unset_count_loop.php:6
        reg_37 = reg_12;
        reg_35 = reg_9;
    // Optimized: structured for loop
    reg_37 = reg_12;
    reg_36 = reg_19;
    reg_35 = reg_9;
    reg_37 = reg_12;
    reg_35 = reg_9;
    while (true) {
        // Header: foreach_cond_0
            // test_unset_count_loop.php:6
    // PHI: reg_37 (handled in terminator)
            // test_unset_count_loop.php:6
    // PHI: reg_36 (handled in terminator)
            // test_unset_count_loop.php:5
    // PHI: reg_35 (handled in terminator)
            // test_unset_count_loop.php:6
    reg_14.release(runtime.runtime_allocator);
    reg_14 = reg_37; // cast from .php_value to .php_value
    _ = reg_14.retain();
            // test_unset_count_loop.php:6
    reg_15.release(runtime.runtime_allocator);
    reg_15 = try runtime.php_array_iter_valid(reg_37);
    if (runtime.hasException()) {
        @branchHint(.unlikely);
        // Cleanup on exception
        reg_0.release(runtime.runtime_allocator);
        reg_7.release(runtime.runtime_allocator);
        reg_12.release(runtime.runtime_allocator);
        reg_15.release(runtime.runtime_allocator);
        reg_19.release(runtime.runtime_allocator);
        reg_24.release(runtime.runtime_allocator);
        reg_26.release(runtime.runtime_allocator);
        reg_28.release(runtime.runtime_allocator);
        reg_29.release(runtime.runtime_allocator);
        reg_30.release(runtime.runtime_allocator);
        reg_32.release(runtime.runtime_allocator);
        reg_33.release(runtime.runtime_allocator);
        reg_34.release(runtime.runtime_allocator);
        return error.RuntimeError;
    }
        if (!(reg_15.asBool())) { @branchHint(.unlikely); break; }
        // Body: foreach_body_1
            // test_unset_count_loop.php:6
    reg_17.release(runtime.runtime_allocator);
    reg_17 = reg_37; // cast from .php_value to .php_value
    _ = reg_17.retain();
            // test_unset_count_loop.php:6
    reg_19 = try runtime.php_array_iter_value(reg_37);
    if (runtime.hasException()) {
        @branchHint(.unlikely);
        // Cleanup on exception
        reg_0.release(runtime.runtime_allocator);
        reg_7.release(runtime.runtime_allocator);
        reg_12.release(runtime.runtime_allocator);
        reg_15.release(runtime.runtime_allocator);
        reg_19.release(runtime.runtime_allocator);
        reg_24.release(runtime.runtime_allocator);
        reg_26.release(runtime.runtime_allocator);
        reg_28.release(runtime.runtime_allocator);
        reg_29.release(runtime.runtime_allocator);
        reg_30.release(runtime.runtime_allocator);
        reg_32.release(runtime.runtime_allocator);
        reg_33.release(runtime.runtime_allocator);
        reg_34.release(runtime.runtime_allocator);
        return error.RuntimeError;
    }
            // test_unset_count_loop.php:6
            // test_unset_count_loop.php:7
    reg_20 = reg_35;
            // test_unset_count_loop.php:7
    reg_21 = reg_19;
            // test_unset_count_loop.php:7
    reg_22 = (try runtime.php_add(runtime.Value.initInt(reg_35), reg_19)).asInt();
            // test_unset_count_loop.php:7
        // Increment: foreach_increment_2 (x1)
            // test_unset_count_loop.php:7
    reg_23.release(runtime.runtime_allocator);
    reg_23 = reg_37; // cast from .php_value to .php_value
    _ = reg_23.retain();
            // test_unset_count_loop.php:7
    reg_24.release(runtime.runtime_allocator);
    reg_24 = try runtime.php_array_iter_next(reg_37);
    if (runtime.hasException()) {
        @branchHint(.unlikely);
        // Cleanup on exception
        reg_0.release(runtime.runtime_allocator);
        reg_7.release(runtime.runtime_allocator);
        reg_12.release(runtime.runtime_allocator);
        reg_15.release(runtime.runtime_allocator);
        reg_19.release(runtime.runtime_allocator);
        reg_24.release(runtime.runtime_allocator);
        reg_26.release(runtime.runtime_allocator);
        reg_28.release(runtime.runtime_allocator);
        reg_29.release(runtime.runtime_allocator);
        reg_30.release(runtime.runtime_allocator);
        reg_32.release(runtime.runtime_allocator);
        reg_33.release(runtime.runtime_allocator);
        reg_34.release(runtime.runtime_allocator);
        return error.RuntimeError;
    }
            // test_unset_count_loop.php:7
        reg_37 = reg_24;
        reg_36 = reg_19.asInt();
        reg_35 = reg_22;
    }
    // Block 4: foreach_exit_3
        // test_unset_count_loop.php:7
    reg_25.release(runtime.runtime_allocator);
    reg_25 = reg_37; // cast from .php_value to .php_value
    _ = reg_25.retain();
        // test_unset_count_loop.php:7
    _ = try runtime.php_array_iter_free(reg_37, runtime.runtime_allocator);
    if (runtime.hasException()) {
        @branchHint(.unlikely);
        // Cleanup on exception
        reg_0.release(runtime.runtime_allocator);
        reg_7.release(runtime.runtime_allocator);
        reg_12.release(runtime.runtime_allocator);
        reg_15.release(runtime.runtime_allocator);
        reg_19.release(runtime.runtime_allocator);
        reg_24.release(runtime.runtime_allocator);
        reg_26.release(runtime.runtime_allocator);
        reg_28.release(runtime.runtime_allocator);
        reg_29.release(runtime.runtime_allocator);
        reg_30.release(runtime.runtime_allocator);
        reg_32.release(runtime.runtime_allocator);
        reg_33.release(runtime.runtime_allocator);
        reg_34.release(runtime.runtime_allocator);
        return error.RuntimeError;
    }
        // test_unset_count_loop.php:9
    reg_26.release(runtime.runtime_allocator);
    reg_26 = runtime.Value.initString(static_strings[5]);
        // test_unset_count_loop.php:9
    reg_27.release(runtime.runtime_allocator);
    reg_27 = reg_7; // cast from .php_value to .php_value
    _ = reg_27.retain();
        // test_unset_count_loop.php:9
    reg_28.release(runtime.runtime_allocator);
    reg_28 = try runtime.php_concat(reg_26, reg_27, runtime.runtime_allocator);
        // test_unset_count_loop.php:9
    reg_29.release(runtime.runtime_allocator);
    reg_29 = runtime.Value.initString(static_strings[6]);
        // test_unset_count_loop.php:9
    reg_30.release(runtime.runtime_allocator);
    reg_30 = try runtime.php_concat(reg_28, reg_29, runtime.runtime_allocator);
        // test_unset_count_loop.php:9
    reg_31 = reg_35;
        // test_unset_count_loop.php:9
    reg_32.release(runtime.runtime_allocator);
    reg_32 = try runtime.php_concat(reg_30, runtime.Value.initInt(reg_31), runtime.runtime_allocator);
        // test_unset_count_loop.php:9
    reg_33.release(runtime.runtime_allocator);
    reg_33 = runtime.Value.initString(static_strings[7]);
        // test_unset_count_loop.php:9
    reg_34.release(runtime.runtime_allocator);
    reg_34 = try runtime.php_concat(reg_32, reg_33, runtime.runtime_allocator);
        // test_unset_count_loop.php:9
    _ = try runtime.php_echo(reg_34);
    if (runtime.hasException()) {
        @branchHint(.unlikely);
        // Cleanup on exception
        reg_0.release(runtime.runtime_allocator);
        reg_7.release(runtime.runtime_allocator);
        reg_12.release(runtime.runtime_allocator);
        reg_15.release(runtime.runtime_allocator);
        reg_19.release(runtime.runtime_allocator);
        reg_24.release(runtime.runtime_allocator);
        reg_26.release(runtime.runtime_allocator);
        reg_28.release(runtime.runtime_allocator);
        reg_29.release(runtime.runtime_allocator);
        reg_30.release(runtime.runtime_allocator);
        reg_32.release(runtime.runtime_allocator);
        reg_33.release(runtime.runtime_allocator);
        reg_34.release(runtime.runtime_allocator);
        return error.RuntimeError;
    }
    return reg_34;
}

pub fn @"select"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_select_builtin(ctx, args, allocator);
}

pub fn @"go"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_go(ctx, args, allocator);
}

pub fn @"go_wait_all"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_go_wait_all(ctx, args, allocator);
}

pub fn @"go_join"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_go_join(ctx, args, allocator);
}

pub fn @"get_class_methods"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_get_class_methods_builtin(ctx, args, allocator);
}

pub fn @"get_class_vars"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_get_class_vars_builtin(ctx, args, allocator);
}

pub fn @"get_object_vars"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_get_object_vars_builtin(ctx, args, allocator);
}

pub fn @"get_called_class"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_get_called_class_builtin(ctx, args, allocator);
}

pub fn @"forward_static_call"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_forward_static_call_builtin(ctx, args, allocator);
}

pub fn @"forward_static_call_array"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_forward_static_call_array_builtin(ctx, args, allocator);
}

fn registerAllClasses(allocator: std.mem.Allocator) !void {
    try runtime.ClassMeta.registerExceptionClass(allocator);
}

fn registerAllFunctions() !void {
}

pub fn main() !void {
    const allocator = std.heap.page_allocator;
    
    runtime.initRuntime(allocator);
    defer runtime.deinitRuntime();

    // 初始化静态字符串池（一次性开销）
    initStaticStrings();

    var profiling_enabled: bool = false;
    if (std.process.getEnvVarOwned(allocator, "ZIGPHP_PROFILE")) |v| {
        profiling_enabled = true;
        allocator.free(v);
    } else |_| {}

    var profiler: runtime.profiler.Profiler = undefined;
    var generator: runtime.flamegraph.FlameGraphGenerator = undefined;

    if (profiling_enabled) {
        profiler = try runtime.profiler.Profiler.init(allocator, .custom);
        profiler.enable();
        runtime.profiler.setGlobalProfiler(&profiler);

        generator = try runtime.flamegraph.FlameGraphGenerator.init(allocator, &profiler);
        generator.setMinDisplayTime(0);
        if (std.process.getEnvVarOwned(allocator, "ZIGPHP_PROFILE_INTERVAL_NS")) |s| {
            defer allocator.free(s);
            generator.setSamplingInterval(std.fmt.parseInt(u64, s, 10) catch generator.sampling_interval_ns);
        } else |_| {}
        try generator.startSampling();
    }

    defer if (profiling_enabled) {
        generator.stopSampling();

        const folded = generator.generateFoldedFormat(allocator) catch null;
        if (folded) |data| {
            defer allocator.free(data);
            const out = std.fs.cwd().createFile("flamegraph.txt", .{}) catch null;
            if (out) |file| {
                defer file.close();
                _ = file.writeAll(data) catch {};
            }
        }

        const pb = std.fs.cwd().createFile("profile.pb", .{}) catch null;
        if (pb) |file| {
            defer file.close();
            var buf: [16 * 1024]u8 = undefined;
            var w = file.writer(&buf);
            runtime.pprof.writeCpuProfileFromFlameGraph(allocator, &w.interface, generator.root, generator.sampling_interval_ns) catch {};
            _ = w.end() catch {};
        }

        generator.deinit();
        runtime.profiler.setGlobalProfiler(null);
        profiler.deinit();
    };
    
    // 注册所有类
    registerAllClasses(allocator) catch {};
    // 注册所有函数
    registerAllFunctions() catch {};
    defer runtime.cleanupAllClasses();
    
    _ = try @"__main__"(runtime.Value.initNull(), &[_]runtime.Value{}, allocator);
    _ = runtime.php_go_wait_all(runtime.Value.initNull(), &[_]runtime.Value{}, allocator) catch {};
}
