// Generated by zig-php AOT compiler
// DO NOT EDIT

const std = @import("std");
const runtime = @import("runtime_lib.zig");

// String table
const string_table = [_][]const u8{
    "$arr",
    "$sum",
    "$i",
    "ArrIdx: ",
    " (expect 10)\n",
};

// 静态字符串池（运行时初始化一次）
var static_strings: [string_table.len]*runtime.PHPString = undefined;
var static_strings_initialized = false;

fn initStaticStrings() void {
    if (static_strings_initialized) return;
    for (string_table, 0..) |str, i| {
        static_strings[i] = runtime.PHPString.initStatic(str);
    }
    static_strings_initialized = true;
}


// MARKER: generateFunction called
pub fn @"__main__"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) !runtime.Value {
    _ = &ctx;
    _ = &args;
    _ = allocator;
    _ = runtime;
    runtime.profiler.enterGlobal("__main__");
    defer runtime.profiler.exitGlobal("__main__");
    // Register declarations
    var reg_20: i64 = 0;
    _ = &reg_20;
    var reg_12: runtime.Value = runtime.Value.initNull();
    _ = &reg_12;
    var reg_21: runtime.Value = runtime.Value.initNull();
    _ = &reg_21;
    var reg_9: runtime.Value = runtime.Value.initNull();
    _ = &reg_9;
    var reg_19: i64 = 0;
    _ = &reg_19;
    var reg_27: i64 = 0;
    _ = &reg_27;
    var reg_3: i64 = 0;
    _ = &reg_3;
    var reg_2: i64 = 0;
    _ = &reg_2;
    var reg_1: i64 = 0;
    _ = &reg_1;
    var reg_22: i64 = 0;
    _ = &reg_22;
    var reg_25: runtime.Value = runtime.Value.initNull();
    _ = &reg_25;
    var reg_15: i64 = 0;
    _ = &reg_15;
    var reg_13: i64 = 0;
    _ = &reg_13;
    var reg_11: i64 = 0;
    _ = &reg_11;
    var reg_7: runtime.Value = runtime.Value.initNull();
    _ = &reg_7;
    var reg_8: i64 = 0;
    _ = &reg_8;
    var reg_10: i64 = 0;
    _ = &reg_10;
    var reg_26: i64 = 0;
    _ = &reg_26;
    var reg_17: i64 = 0;
    _ = &reg_17;
    var reg_14: runtime.Value = runtime.Value.initNull();
    _ = &reg_14;
    var reg_23: runtime.Value = runtime.Value.initNull();
    _ = &reg_23;
    var reg_0: runtime.Value = runtime.Value.initNull();
    _ = &reg_0;
    var reg_4: i64 = 0;
    _ = &reg_4;
    var reg_6: i64 = 0;
    _ = &reg_6;
    var reg_18: i64 = 0;
    _ = &reg_18;
    var reg_5: runtime.Value = runtime.Value.initNull();
    _ = &reg_5;
    var reg_16: i64 = 0;
    _ = &reg_16;
    var reg_24: runtime.Value = runtime.Value.initNull();
    _ = &reg_24;

    // Block 0: entry
            // test_array_index_sum.php:3
    // test_array_index_sum.php:3
            // test_array_index_sum.php:4
    // test_array_index_sum.php:4
            // test_array_index_sum.php:5
    // test_array_index_sum.php:5
            // test_array_index_sum.php:3
        reg_0 = runtime.Value.initArray(try runtime.PHPArray.init(runtime.runtime_allocator));
            // test_array_index_sum.php:3
        reg_1 = 1;
            // test_array_index_sum.php:3
        try reg_0.asArray().push(runtime.runtime_allocator, runtime.Value.initInt(reg_1));
            // test_array_index_sum.php:3
        reg_2 = 2;
            // test_array_index_sum.php:3
        try reg_0.asArray().push(runtime.runtime_allocator, runtime.Value.initInt(reg_2));
            // test_array_index_sum.php:3
        reg_3 = 3;
            // test_array_index_sum.php:3
        try reg_0.asArray().push(runtime.runtime_allocator, runtime.Value.initInt(reg_3));
            // test_array_index_sum.php:3
        reg_4 = 4;
            // test_array_index_sum.php:3
        try reg_0.asArray().push(runtime.runtime_allocator, runtime.Value.initInt(reg_4));
            // test_array_index_sum.php:3
    // test_array_index_sum.php:3
            // test_array_index_sum.php:4
        reg_6 = 0;
            // test_array_index_sum.php:4
    // test_array_index_sum.php:4
    // Block 1: for_init_0
            // test_array_index_sum.php:5
        reg_8 = 0;
            // test_array_index_sum.php:5
    // test_array_index_sum.php:5
        reg_27 = reg_8;
        reg_26 = reg_6;
    // Optimized: structured for loop
    reg_27 = reg_8;
    reg_26 = reg_6;
        // test_array_index_sum.php:5
    reg_11 = 4;
        // test_array_index_sum.php:5
    reg_19 = 1;
    reg_27 = reg_8;
    reg_26 = reg_6;
    while (true) {
        // Header: for_cond_1
            // test_array_index_sum.php:5
    // PHI: reg_27 (handled in terminator)
            // test_array_index_sum.php:4
    // PHI: reg_26 (handled in terminator)
            // test_array_index_sum.php:5
    reg_10 = reg_27;
        if (!(reg_27 < reg_11)) { @branchHint(.unlikely); break; }
        // Body: for_body_2
            // test_array_index_sum.php:6
    reg_13 = reg_26;
            // test_array_index_sum.php:6
    reg_14.release(runtime.runtime_allocator);
    reg_14 = reg_0; // cast from .php_array to .php_value
            // test_array_index_sum.php:6
    reg_15 = reg_27;
            // test_array_index_sum.php:6
    reg_16 = (reg_0.asArray().get(runtime.ArrayKey{ .integer = reg_27 }) orelse runtime.Value.initNull()).asInt();
            // test_array_index_sum.php:6
    reg_17 = reg_26 + reg_16;
            // test_array_index_sum.php:6
        // Increment: for_loop_3 (x1)
            // test_array_index_sum.php:5
    reg_18 = reg_27;
            // test_array_index_sum.php:5
    reg_20 = reg_27 + reg_19;
            // test_array_index_sum.php:5
        reg_27 = reg_20;
        reg_26 = reg_17;
    }
    // Block 5: for_exit_4
        // test_array_index_sum.php:8
    reg_21.release(runtime.runtime_allocator);
    reg_21 = runtime.Value.initString(static_strings[3]);
        // test_array_index_sum.php:8
    reg_22 = reg_26;
        // test_array_index_sum.php:8
    reg_23.release(runtime.runtime_allocator);
    reg_23 = try runtime.php_concat(reg_21, runtime.Value.initInt(reg_22), runtime.runtime_allocator);
        // test_array_index_sum.php:8
    reg_24.release(runtime.runtime_allocator);
    reg_24 = runtime.Value.initString(static_strings[4]);
        // test_array_index_sum.php:8
    reg_25.release(runtime.runtime_allocator);
    reg_25 = try runtime.php_concat(reg_23, reg_24, runtime.runtime_allocator);
        // test_array_index_sum.php:8
    _ = try runtime.php_echo(reg_25);
    if (runtime.hasException()) {
        @branchHint(.unlikely);
        // Cleanup on exception
        reg_0.release(runtime.runtime_allocator);
        reg_21.release(runtime.runtime_allocator);
        reg_23.release(runtime.runtime_allocator);
        reg_24.release(runtime.runtime_allocator);
        reg_25.release(runtime.runtime_allocator);
        return error.RuntimeError;
    }
    return reg_25;
}

pub fn @"select"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_select_builtin(ctx, args, allocator);
}

pub fn @"go"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_go(ctx, args, allocator);
}

pub fn @"go_wait_all"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_go_wait_all(ctx, args, allocator);
}

pub fn @"go_join"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_go_join(ctx, args, allocator);
}

pub fn @"get_class_methods"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_get_class_methods_builtin(ctx, args, allocator);
}

pub fn @"get_class_vars"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_get_class_vars_builtin(ctx, args, allocator);
}

pub fn @"get_object_vars"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_get_object_vars_builtin(ctx, args, allocator);
}

pub fn @"get_called_class"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_get_called_class_builtin(ctx, args, allocator);
}

pub fn @"forward_static_call"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_forward_static_call_builtin(ctx, args, allocator);
}

pub fn @"forward_static_call_array"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_forward_static_call_array_builtin(ctx, args, allocator);
}

fn registerAllClasses(allocator: std.mem.Allocator) !void {
    try runtime.ClassMeta.registerExceptionClass(allocator);
}

fn registerAllFunctions() !void {
}

pub fn main() !void {
    const allocator = std.heap.page_allocator;
    
    runtime.initRuntime(allocator);
    defer runtime.deinitRuntime();

    // 初始化静态字符串池（一次性开销）
    initStaticStrings();

    var profiling_enabled: bool = false;
    if (std.process.getEnvVarOwned(allocator, "ZIGPHP_PROFILE")) |v| {
        profiling_enabled = true;
        allocator.free(v);
    } else |_| {}

    var profiler: runtime.profiler.Profiler = undefined;
    var generator: runtime.flamegraph.FlameGraphGenerator = undefined;

    if (profiling_enabled) {
        profiler = try runtime.profiler.Profiler.init(allocator, .custom);
        profiler.enable();
        runtime.profiler.setGlobalProfiler(&profiler);

        generator = try runtime.flamegraph.FlameGraphGenerator.init(allocator, &profiler);
        generator.setMinDisplayTime(0);
        if (std.process.getEnvVarOwned(allocator, "ZIGPHP_PROFILE_INTERVAL_NS")) |s| {
            defer allocator.free(s);
            generator.setSamplingInterval(std.fmt.parseInt(u64, s, 10) catch generator.sampling_interval_ns);
        } else |_| {}
        try generator.startSampling();
    }

    defer if (profiling_enabled) {
        generator.stopSampling();

        const folded = generator.generateFoldedFormat(allocator) catch null;
        if (folded) |data| {
            defer allocator.free(data);
            const out = std.fs.cwd().createFile("flamegraph.txt", .{}) catch null;
            if (out) |file| {
                defer file.close();
                _ = file.writeAll(data) catch {};
            }
        }

        const pb = std.fs.cwd().createFile("profile.pb", .{}) catch null;
        if (pb) |file| {
            defer file.close();
            var buf: [16 * 1024]u8 = undefined;
            var w = file.writer(&buf);
            runtime.pprof.writeCpuProfileFromFlameGraph(allocator, &w.interface, generator.root, generator.sampling_interval_ns) catch {};
            _ = w.end() catch {};
        }

        generator.deinit();
        runtime.profiler.setGlobalProfiler(null);
        profiler.deinit();
    };
    
    // 注册所有类
    registerAllClasses(allocator) catch {};
    // 注册所有函数
    registerAllFunctions() catch {};
    defer runtime.cleanupAllClasses();
    
    _ = try @"__main__"(runtime.Value.initNull(), &[_]runtime.Value{}, allocator);
    _ = runtime.php_go_wait_all(runtime.Value.initNull(), &[_]runtime.Value{}, allocator) catch {};
}
