// Generated by zig-php AOT compiler
// DO NOT EDIT

const std = @import("std");
const runtime = @import("runtime_lib.zig");

// String table
const string_table = [_][]const u8{
    "$a",
};

// 静态字符串池（运行时初始化一次）
var static_strings: [string_table.len]*runtime.PHPString = undefined;
var static_strings_initialized = false;

fn initStaticStrings() void {
    if (static_strings_initialized) return;
    for (string_table, 0..) |str, i| {
        static_strings[i] = runtime.PHPString.initStatic(str);
    }
    static_strings_initialized = true;
}


// MARKER: generateFunction called
pub fn @"__main__"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) !runtime.Value {
    _ = &ctx;
    _ = &args;
    _ = allocator;
    _ = runtime;
    runtime.profiler.enterGlobal("__main__");
    defer runtime.profiler.exitGlobal("__main__");
    // Register declarations
    var reg_7: runtime.Value = runtime.Value.initNull();
    _ = &reg_7;
    var reg_1: runtime.Value = runtime.Value.initNull();
    _ = &reg_1;
    var reg_0: runtime.Value = runtime.Value.initNull();
    _ = &reg_0;
    var reg_4: runtime.Value = runtime.Value.initNull();
    _ = &reg_4;
    var reg_6: runtime.Value = runtime.Value.initNull();
    _ = &reg_6;
    var reg_8: runtime.Value = runtime.Value.initNull();
    _ = &reg_8;
    var reg_5: runtime.Value = runtime.Value.initNull();
    _ = &reg_5;
    var reg_9: runtime.Value = runtime.Value.initNull();
    _ = &reg_9;
    var reg_2: runtime.Value = runtime.Value.initNull();
    _ = &reg_2;
    var reg_3: runtime.Value = runtime.Value.initNull();
    _ = &reg_3;

    var null_val = runtime.Value.initNull();
    _ = &null_val;

    // Instructions
    // test_debug.php:2
    reg_0 = runtime.Value.initInt(5);
    // test_debug.php:2
    try setGlobalVar("$a", reg_0);
    // test_debug.php:3
    reg_1.release(runtime.runtime_allocator);
    reg_1 = getGlobalVar("$a");
    // test_debug.php:3
    reg_2.release(runtime.runtime_allocator);
    reg_2 = getGlobalVar("$a");
    // test_debug.php:3
    reg_3 = runtime.Value.initInt(1);
    // test_debug.php:3
    reg_4 = try runtime.php_add(reg_2, reg_3);
    // test_debug.php:3
    try setGlobalVar("$a", reg_4);
    // test_debug.php:3
    reg_5.release(runtime.runtime_allocator);
    reg_5 = try runtime.php_concat(reg_1, reg_2, runtime.runtime_allocator);
    // test_debug.php:3
    reg_6.release(runtime.runtime_allocator);
    reg_6 = getGlobalVar("$a");
    // test_debug.php:3
    reg_7.release(runtime.runtime_allocator);
    reg_7 = try runtime.php_concat(reg_5, reg_6, runtime.runtime_allocator);
    // test_debug.php:3
    reg_8 = runtime.Value.initInt(1);
    // test_debug.php:3
    reg_9 = try runtime.php_add(reg_7, reg_8);
    // test_debug.php:3
    _ = try runtime.php_echo(reg_9);
    if (runtime.hasException()) {
        @branchHint(.unlikely);
        // Cleanup on exception
        reg_5.release(runtime.runtime_allocator);
        reg_5 = runtime.Value.initNull();
        reg_7.release(runtime.runtime_allocator);
        reg_7 = runtime.Value.initNull();
        return error.RuntimeError;
    }

    // Cleanup: release allocated values (except return value)
    if (!reg_5.isNull()) reg_5.release(runtime.runtime_allocator);
    if (!reg_7.isNull()) reg_7.release(runtime.runtime_allocator);
    return runtime.Value.initNull();
}

pub fn @"select"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_select_builtin(ctx, args, allocator);
}

pub fn @"go"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_go(ctx, args, allocator);
}

pub fn @"go_wait_all"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_go_wait_all(ctx, args, allocator);
}

pub fn @"go_join"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_go_join(ctx, args, allocator);
}

pub fn @"get_class_methods"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_get_class_methods_builtin(ctx, args, allocator);
}

pub fn @"get_class_vars"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_get_class_vars_builtin(ctx, args, allocator);
}

pub fn @"get_object_vars"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_get_object_vars_builtin(ctx, args, allocator);
}

pub fn @"get_called_class"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_get_called_class_builtin(ctx, args, allocator);
}

pub fn @"forward_static_call"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_forward_static_call_builtin(ctx, args, allocator);
}

pub fn @"forward_static_call_array"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_forward_static_call_array_builtin(ctx, args, allocator);
}

fn registerAllClasses(allocator: std.mem.Allocator) !void {
    try runtime.ClassMeta.registerExceptionClass(allocator);
}

fn registerAllFunctions() !void {
}

// 全局变量表
var global_vars: std.StringHashMap(runtime.Value) = undefined;
var global_vars_initialized: bool = false;

pub fn getGlobalVar(name: []const u8) runtime.Value {
    // 先查找常量表
    if (runtime.constants.get(name)) |const_val| {
        _ = const_val.retain();
        return const_val;
    }
    // 再查找全局变量表
    if (!global_vars_initialized) return runtime.Value.initNull();
    const value = global_vars.get(name) orelse runtime.Value.initNull();
    _ = value.retain();
    return value;
}

pub fn setGlobalVar(name: []const u8, value: runtime.Value) !void {
    if (!global_vars_initialized) return;
    // Check if key already exists
    const gop = try global_vars.getOrPut(name);
    if (!gop.found_existing) {
        // Need to duplicate the key for new entries
        const key_copy = try runtime.runtime_allocator.dupe(u8, name);
        gop.key_ptr.* = key_copy;
        // Retain the new value
        _ = value.retain();
        gop.value_ptr.* = value;
    } else {
        // Release old value and retain new value
        gop.value_ptr.release(runtime.runtime_allocator);
        _ = value.retain();
        gop.value_ptr.* = value;
    }
}

pub fn unsetGlobalVar(name_val: runtime.Value) !void {
    if (!global_vars_initialized) return;
    if (!name_val.isString()) return;
    const name = name_val.asString().data;
    // 从全局变量表中删除并释放
    if (global_vars.getPtr(name)) |val_ptr| {
        // Release setGlobalVar的retain
        val_ptr.release(runtime.runtime_allocator);
        // 从表中删除
        if (global_vars.fetchRemove(name)) |kv| {
            runtime.runtime_allocator.free(kv.key);
        }
    }
}

pub fn getGlobalVarDynamic(name_val: runtime.Value) !runtime.Value {
    const name_str = try name_val.toString(runtime.runtime_allocator);
    defer name_str.release(runtime.runtime_allocator);
    return getGlobalVar(name_str.data);
}

pub fn setGlobalVarDynamic(name_val: runtime.Value, value: runtime.Value) !void {
    const name_str = try name_val.toString(runtime.runtime_allocator);
    defer name_str.release(runtime.runtime_allocator);
    // Add $ prefix if not present
    if (name_str.data.len > 0 and name_str.data[0] == '$') {
        try setGlobalVar(name_str.data, value);
    } else {
        const prefixed = try std.fmt.allocPrint(runtime.runtime_allocator, "${s}", .{name_str.data});
        defer runtime.runtime_allocator.free(prefixed);
        try setGlobalVar(prefixed, value);
    }
}

pub fn main() !void {
    const allocator = std.heap.page_allocator;

    runtime.initRuntime(allocator);
    defer runtime.deinitRuntime();

    // 初始化全局变量表
    global_vars = std.StringHashMap(runtime.Value).init(allocator);
    global_vars_initialized = true;
    defer {
        var it = global_vars.valueIterator();
        while (it.next()) |val| {
            val.release(runtime.runtime_allocator);
        }
        global_vars.deinit();
    }
    // 初始化静态字符串池（一次性开销）
    initStaticStrings();
    // 初始化PHP预定义常量
    {
        const key1 = try allocator.dupeZ(u8, "COUNT_RECURSIVE");
        try runtime.constants.put(key1, runtime.Value.initInt(1));
        const key2 = try allocator.dupeZ(u8, "COUNT_NORMAL");
        try runtime.constants.put(key2, runtime.Value.initInt(0));
    }
    var alloc_stats_enabled: bool = false;
    if (std.process.getEnvVarOwned(allocator, "ZIGPHP_ALLOC_STATS")) |v| {
        alloc_stats_enabled = true;
        allocator.free(v);
    } else |_| {}

    defer if (alloc_stats_enabled) {
        const s = runtime.getAllocStats();
        std.debug.print(
            "ALLOC_STATS alloc_bytes={d} alloc_count={d} free_bytes={d} free_count={d} live_bytes={d} live_allocs={d} peak_live_bytes={d} peak_live_allocs={d} php_string_live_objects={d} php_string_live_bytes={d} php_array_live_objects={d} php_object_live_objects={d}\\n",
            .{ s.alloc_bytes, s.alloc_count, s.free_bytes, s.free_count, s.live_bytes, s.live_allocs, s.peak_live_bytes, s.peak_live_allocs, s.php_string_live_objects, s.php_string_live_bytes, s.php_array_live_objects, s.php_object_live_objects },
        );
    };

    var profiling_enabled: bool = false;
    if (std.process.getEnvVarOwned(allocator, "ZIGPHP_PROFILE")) |v| {
        profiling_enabled = true;
        allocator.free(v);
    } else |_| {}

    var profiler: runtime.profiler.Profiler = undefined;
    var generator: runtime.flamegraph.FlameGraphGenerator = undefined;

    if (profiling_enabled) {
        profiler = try runtime.profiler.Profiler.init(allocator, .custom);
        profiler.enable();
        runtime.profiler.setGlobalProfiler(&profiler);

        generator = try runtime.flamegraph.FlameGraphGenerator.init(allocator, &profiler);
        generator.setMinDisplayTime(0);
        if (std.process.getEnvVarOwned(allocator, "ZIGPHP_PROFILE_INTERVAL_NS")) |s| {
            defer allocator.free(s);
            generator.setSamplingInterval(std.fmt.parseInt(u64, s, 10) catch generator.sampling_interval_ns);
        } else |_| {}
        try generator.startSampling();
    }

    defer if (profiling_enabled) {
        generator.stopSampling();

        const folded = generator.generateFoldedFormat(allocator) catch null;
        if (folded) |data| {
            defer allocator.free(data);
            const out = std.fs.cwd().createFile("flamegraph.txt", .{}) catch null;
            if (out) |file| {
                defer file.close();
                _ = file.writeAll(data) catch {};
            }
        }

        const pb = std.fs.cwd().createFile("profile.pb", .{}) catch null;
        if (pb) |file| {
            defer file.close();
            var buf: [16 * 1024]u8 = undefined;
            var w = file.writer(&buf);
            runtime.pprof.writeCpuProfileFromFlameGraph(allocator, &w.interface, generator.root, generator.sampling_interval_ns) catch {};
            _ = w.end() catch {};
        }

        generator.deinit();
        runtime.profiler.setGlobalProfiler(null);
        profiler.deinit();
    };

    // 注册所有类
    registerAllClasses(allocator) catch {};
    // 注册所有函数
    registerAllFunctions() catch {};
    defer runtime.cleanupAllClasses();

    _ = try @"__main__"(runtime.Value.initNull(), &[_]runtime.Value{}, allocator);
    _ = runtime.php_go_wait_all(runtime.Value.initNull(), &[_]runtime.Value{}, allocator) catch {};
}
