// Generated by zig-php AOT compiler
// DO NOT EDIT

const std = @import("std");
const runtime = @import("runtime_lib.zig");

// String table
const string_table = [_][]const u8{
    "$arr",
    "$v",
    "print_r",
};

// 静态字符串池（运行时初始化一次）
var static_strings: [string_table.len]*runtime.PHPString = undefined;
var static_strings_initialized = false;

fn initStaticStrings() void {
    if (static_strings_initialized) return;
    for (string_table, 0..) |str, i| {
        static_strings[i] = runtime.PHPString.initStatic(str);
    }
    static_strings_initialized = true;
}


// MARKER: generateFunction called
pub fn @"__main__"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) !runtime.Value {
    _ = &ctx;
    _ = &args;
    _ = allocator;
    _ = runtime;
    runtime.profiler.enterGlobal("__main__");
    defer runtime.profiler.exitGlobal("__main__");
    // Register declarations
    var reg_10: bool = false;
    _ = &reg_10;
    var reg_12: runtime.Value = runtime.Value.initNull();
    _ = &reg_12;
    var reg_20: bool = false;
    _ = &reg_20;
    var reg_21: runtime.Value = runtime.Value.initNull();
    _ = &reg_21;
    var reg_17: runtime.Value = runtime.Value.initNull();
    _ = &reg_17;
    var reg_9: runtime.Value = runtime.Value.initNull();
    _ = &reg_9;
    var reg_19: runtime.Value = runtime.Value.initNull();
    _ = &reg_19;
    var reg_14: runtime.Value = runtime.Value.initNull();
    _ = &reg_14;
    var reg_2: i64 = 0;
    _ = &reg_2;
    var reg_3: i64 = 0;
    _ = &reg_3;
    var reg_1: i64 = 0;
    _ = &reg_1;
    var reg_0: runtime.Value = runtime.Value.initNull();
    _ = &reg_0;
    var reg_4: runtime.Value = runtime.Value.initNull();
    _ = &reg_4;
    var reg_6: runtime.Value = runtime.Value.initNull();
    _ = &reg_6;
    var reg_23: runtime.Value = runtime.Value.initNull();
    _ = &reg_23;
    var reg_22: runtime.Value = runtime.Value.initNull();
    _ = &reg_22;
    var reg_15: runtime.Value = runtime.Value.initNull();
    _ = &reg_15;
    var reg_18: runtime.Value = runtime.Value.initNull();
    _ = &reg_18;
    var reg_13: i64 = 0;
    _ = &reg_13;
    var reg_5: runtime.Value = runtime.Value.initNull();
    _ = &reg_5;
    var reg_11: runtime.Value = runtime.Value.initNull();
    _ = &reg_11;
    var reg_16: runtime.Value = runtime.Value.initNull();
    _ = &reg_16;
    var reg_7: runtime.Value = runtime.Value.initNull();
    _ = &reg_7;
    var reg_8: runtime.Value = runtime.Value.initNull();
    _ = &reg_8;

    // Block 0: entry
            // test_ref.php:2
    // test_ref.php:2
            // test_ref.php:4
    // test_ref.php:4
            // test_ref.php:2
        reg_0 = runtime.Value.initArray(try runtime.PHPArray.init(runtime.runtime_allocator));
            // test_ref.php:2
        reg_1 = 1;
            // test_ref.php:2
        try reg_0.asArray().push(runtime.runtime_allocator, runtime.Value.initInt(reg_1));
            // test_ref.php:2
        reg_2 = 2;
            // test_ref.php:2
        try reg_0.asArray().push(runtime.runtime_allocator, runtime.Value.initInt(reg_2));
            // test_ref.php:2
        reg_3 = 3;
            // test_ref.php:2
        try reg_0.asArray().push(runtime.runtime_allocator, runtime.Value.initInt(reg_3));
            // test_ref.php:2
    // test_ref.php:2
            // test_ref.php:3
        reg_5 = reg_0;
            // test_ref.php:3
        reg_6 = try runtime.php_array_iter_init(reg_0, runtime.runtime_allocator);
            // test_ref.php:3
    // test_ref.php:3
            // test_ref.php:3
    // test_ref.php:3
        reg_23 = reg_6;
    // Optimized: structured for loop
    reg_23 = reg_6;
    reg_22 = reg_14;
        // test_ref.php:4
    reg_12 = runtime.Value.initNull();
        // test_ref.php:4
    reg_13 = 2;
    reg_23 = reg_6;
    while (true) {
        // Header: foreach_cond_0
            // test_ref.php:3
    // PHI: reg_23 (handled in terminator)
            // test_ref.php:4
    // PHI: reg_22 (handled in terminator)
            // test_ref.php:3
    reg_8.release(runtime.runtime_allocator);
    reg_8 = reg_23; // cast from .php_value to .php_value
    _ = reg_8.retain();
            // test_ref.php:3
    reg_9.release(runtime.runtime_allocator);
    reg_9 = try runtime.php_array_iter_valid(reg_23);
    if (runtime.hasException()) {
        @branchHint(.unlikely);
        // Cleanup on exception
        reg_0.release(runtime.runtime_allocator);
        reg_6.release(runtime.runtime_allocator);
        reg_9.release(runtime.runtime_allocator);
        reg_17.release(runtime.runtime_allocator);
        reg_21.release(runtime.runtime_allocator);
        return error.RuntimeError;
    }
        if (!(reg_9.asBool())) { @branchHint(.unlikely); break; }
        // Body: foreach_body_1
            // test_ref.php:3
    reg_11.release(runtime.runtime_allocator);
    reg_11 = reg_23; // cast from .php_value to .php_value
    _ = reg_11.retain();
            // test_ref.php:4
    reg_14 = try runtime.php_mul(reg_12, runtime.Value.initInt(reg_13));
            // test_ref.php:4
        // Increment: foreach_increment_2 (x1)
            // test_ref.php:4
    reg_16.release(runtime.runtime_allocator);
    reg_16 = reg_23; // cast from .php_value to .php_value
    _ = reg_16.retain();
            // test_ref.php:4
    reg_17.release(runtime.runtime_allocator);
    reg_17 = try runtime.php_array_iter_next(reg_23);
    if (runtime.hasException()) {
        @branchHint(.unlikely);
        // Cleanup on exception
        reg_0.release(runtime.runtime_allocator);
        reg_6.release(runtime.runtime_allocator);
        reg_9.release(runtime.runtime_allocator);
        reg_17.release(runtime.runtime_allocator);
        reg_21.release(runtime.runtime_allocator);
        return error.RuntimeError;
    }
            // test_ref.php:4
        reg_23 = reg_17;
        reg_22 = reg_14;
    }
    // Block 4: foreach_exit_3
        // test_ref.php:4
    reg_18.release(runtime.runtime_allocator);
    reg_18 = reg_23; // cast from .php_value to .php_value
    _ = reg_18.retain();
        // test_ref.php:4
    _ = try runtime.php_array_iter_free(reg_23, runtime.runtime_allocator);
    if (runtime.hasException()) {
        @branchHint(.unlikely);
        // Cleanup on exception
        reg_0.release(runtime.runtime_allocator);
        reg_6.release(runtime.runtime_allocator);
        reg_9.release(runtime.runtime_allocator);
        reg_17.release(runtime.runtime_allocator);
        reg_21.release(runtime.runtime_allocator);
        return error.RuntimeError;
    }
        // test_ref.php:6
    reg_19.release(runtime.runtime_allocator);
    reg_19 = reg_0; // cast from .php_array to .php_value
    _ = reg_19.retain();
        // test_ref.php:6
    reg_20 = false;
        // test_ref.php:6
    reg_21.release(runtime.runtime_allocator);
    reg_21 = try runtime.print_r(reg_0, runtime.Value.initBool(reg_20));
    if (runtime.hasException()) {
        @branchHint(.unlikely);
        // Cleanup on exception
        reg_0.release(runtime.runtime_allocator);
        reg_6.release(runtime.runtime_allocator);
        reg_9.release(runtime.runtime_allocator);
        reg_17.release(runtime.runtime_allocator);
        reg_21.release(runtime.runtime_allocator);
        return error.RuntimeError;
    }
    return reg_21;
}

pub fn @"select"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_select_builtin(ctx, args, allocator);
}

pub fn @"go"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_go(ctx, args, allocator);
}

pub fn @"go_wait_all"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_go_wait_all(ctx, args, allocator);
}

pub fn @"go_join"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_go_join(ctx, args, allocator);
}

pub fn @"get_class_methods"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_get_class_methods_builtin(ctx, args, allocator);
}

pub fn @"get_class_vars"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_get_class_vars_builtin(ctx, args, allocator);
}

pub fn @"get_object_vars"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_get_object_vars_builtin(ctx, args, allocator);
}

pub fn @"get_called_class"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_get_called_class_builtin(ctx, args, allocator);
}

pub fn @"forward_static_call"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_forward_static_call_builtin(ctx, args, allocator);
}

pub fn @"forward_static_call_array"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_forward_static_call_array_builtin(ctx, args, allocator);
}

fn registerAllClasses(allocator: std.mem.Allocator) !void {
    try runtime.ClassMeta.registerExceptionClass(allocator);
}

fn registerAllFunctions() !void {
}

pub fn main() !void {
    const allocator = std.heap.page_allocator;

    runtime.initRuntime(allocator);
    defer runtime.deinitRuntime();

    // 初始化静态字符串池（一次性开销）
    initStaticStrings();

    var alloc_stats_enabled: bool = false;
    if (std.process.getEnvVarOwned(allocator, "ZIGPHP_ALLOC_STATS")) |v| {
        alloc_stats_enabled = true;
        allocator.free(v);
    } else |_| {}

    defer if (alloc_stats_enabled) {
        const s = runtime.getAllocStats();
        std.debug.print(
            "ALLOC_STATS alloc_bytes={d} alloc_count={d} free_bytes={d} free_count={d} live_bytes={d} live_allocs={d} peak_live_bytes={d} peak_live_allocs={d} php_string_live_objects={d} php_string_live_bytes={d} php_array_live_objects={d} php_object_live_objects={d}\\n",
            .{ s.alloc_bytes, s.alloc_count, s.free_bytes, s.free_count, s.live_bytes, s.live_allocs, s.peak_live_bytes, s.peak_live_allocs, s.php_string_live_objects, s.php_string_live_bytes, s.php_array_live_objects, s.php_object_live_objects },
        );
    };

    var profiling_enabled: bool = false;
    if (std.process.getEnvVarOwned(allocator, "ZIGPHP_PROFILE")) |v| {
        profiling_enabled = true;
        allocator.free(v);
    } else |_| {}

    var profiler: runtime.profiler.Profiler = undefined;
    var generator: runtime.flamegraph.FlameGraphGenerator = undefined;

    if (profiling_enabled) {
        profiler = try runtime.profiler.Profiler.init(allocator, .custom);
        profiler.enable();
        runtime.profiler.setGlobalProfiler(&profiler);

        generator = try runtime.flamegraph.FlameGraphGenerator.init(allocator, &profiler);
        generator.setMinDisplayTime(0);
        if (std.process.getEnvVarOwned(allocator, "ZIGPHP_PROFILE_INTERVAL_NS")) |s| {
            defer allocator.free(s);
            generator.setSamplingInterval(std.fmt.parseInt(u64, s, 10) catch generator.sampling_interval_ns);
        } else |_| {}
        try generator.startSampling();
    }

    defer if (profiling_enabled) {
        generator.stopSampling();

        const folded = generator.generateFoldedFormat(allocator) catch null;
        if (folded) |data| {
            defer allocator.free(data);
            const out = std.fs.cwd().createFile("flamegraph.txt", .{}) catch null;
            if (out) |file| {
                defer file.close();
                _ = file.writeAll(data) catch {};
            }
        }

        const pb = std.fs.cwd().createFile("profile.pb", .{}) catch null;
        if (pb) |file| {
            defer file.close();
            var buf: [16 * 1024]u8 = undefined;
            var w = file.writer(&buf);
            runtime.pprof.writeCpuProfileFromFlameGraph(allocator, &w.interface, generator.root, generator.sampling_interval_ns) catch {};
            _ = w.end() catch {};
        }

        generator.deinit();
        runtime.profiler.setGlobalProfiler(null);
        profiler.deinit();
    };

    // 注册所有类
    registerAllClasses(allocator) catch {};
    // 注册所有函数
    registerAllFunctions() catch {};
    defer runtime.cleanupAllClasses();

    _ = try @"__main__"(runtime.Value.initNull(), &[_]runtime.Value{}, allocator);
    _ = runtime.php_go_wait_all(runtime.Value.initNull(), &[_]runtime.Value{}, allocator) catch {};
}
