// Generated by zig-php AOT compiler
// DO NOT EDIT

const std = @import("std");
const runtime = @import("runtime_lib.zig");

// String table
const string_table = [_][]const u8{
    "Hello from AOT compiled PHP!\n",
    "$x",
    "$y",
    "$sum",
    "Sum: ",
    "\n",
    "add",
    "$a",
    "$b",
    "$result",
    "Result: ",
};


pub fn @"add"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) !runtime.Value {
    _ = &ctx;
    _ = &args;
    _ = allocator;
    _ = runtime;
    // Register declarations
    var reg_1: runtime.Value = runtime.Value.initNull();
    _ = &reg_1;
    var reg_0_storage: runtime.Value = runtime.Value.initNull();
    const reg_0: *runtime.Value = &reg_0_storage;
    _ = &reg_0;
    var reg_4: runtime.Value = runtime.Value.initNull();
    _ = &reg_4;
    var reg_6: runtime.Value = runtime.Value.initNull();
    _ = &reg_6;
    var reg_5: runtime.Value = runtime.Value.initNull();
    _ = &reg_5;
    var reg_2_storage: runtime.Value = runtime.Value.initNull();
    const reg_2: *runtime.Value = &reg_2_storage;
    _ = &reg_2;
    var reg_3: runtime.Value = runtime.Value.initNull();
    _ = &reg_3;

    // Instructions
    // simple_aot_test.php:12
    // simple_aot_test.php:12
    // simple_aot_test.php:12
    reg_1 = if (args.len > 0 and !args[0].isMissing()) args[0] else runtime.Value.initNull();
    // simple_aot_test.php:12
    reg_0.release(runtime.runtime_allocator);
    reg_1.retain();
    runtime.val_assign(reg_0, reg_1);
    // simple_aot_test.php:12
    reg_3 = if (args.len > 1 and !args[1].isMissing()) args[1] else runtime.Value.initNull();
    // simple_aot_test.php:12
    reg_2.release(runtime.runtime_allocator);
    reg_3.retain();
    runtime.val_assign(reg_2, reg_3);
    // simple_aot_test.php:13
    reg_4.release(runtime.runtime_allocator);
    reg_4 = runtime.val_deref(reg_0).*;
    reg_4.retain();
    // simple_aot_test.php:13
    reg_5.release(runtime.runtime_allocator);
    reg_5 = runtime.val_deref(reg_2).*;
    reg_5.retain();
    // simple_aot_test.php:13
    reg_6 = try runtime.php_add(reg_4, reg_5);

    // Cleanup: release allocated values (except return value)
    reg_2.*.release(runtime.runtime_allocator);
    reg_0.*.release(runtime.runtime_allocator);
    reg_4.release(runtime.runtime_allocator);
    reg_5.release(runtime.runtime_allocator);
    return reg_6;
}

pub fn @"__main__"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) !runtime.Value {
    _ = &ctx;
    _ = &args;
    _ = allocator;
    _ = runtime;
    // Register declarations
    var reg_10: i64 = 0;
    _ = &reg_10;
    var reg_12: runtime.Value = runtime.Value.initNull();
    _ = &reg_12;
    var reg_20: runtime.Value = runtime.Value.initNull();
    _ = &reg_20;
    var reg_21: runtime.Value = runtime.Value.initNull();
    _ = &reg_21;
    var reg_17_storage: runtime.Value = runtime.Value.initNull();
    const reg_17: *runtime.Value = &reg_17_storage;
    _ = &reg_17;
    var reg_9: runtime.Value = runtime.Value.initNull();
    _ = &reg_9;
    var reg_19: runtime.Value = runtime.Value.initNull();
    _ = &reg_19;
    var reg_14: i64 = 0;
    _ = &reg_14;
    var reg_2_storage: runtime.Value = runtime.Value.initNull();
    const reg_2: *runtime.Value = &reg_2_storage;
    _ = &reg_2;
    var reg_3: i64 = 0;
    _ = &reg_3;
    var reg_1: i64 = 0;
    _ = &reg_1;
    var reg_0: runtime.Value = runtime.Value.initNull();
    _ = &reg_0;
    var reg_4_storage: runtime.Value = runtime.Value.initNull();
    const reg_4: *runtime.Value = &reg_4_storage;
    _ = &reg_4;
    var reg_6: i64 = 0;
    _ = &reg_6;
    var reg_18: runtime.Value = runtime.Value.initNull();
    _ = &reg_18;
    var reg_22: runtime.Value = runtime.Value.initNull();
    _ = &reg_22;
    var reg_15: i64 = 0;
    _ = &reg_15;
    var reg_13: runtime.Value = runtime.Value.initNull();
    _ = &reg_13;
    var reg_5: i64 = 0;
    _ = &reg_5;
    var reg_11: runtime.Value = runtime.Value.initNull();
    _ = &reg_11;
    var reg_16: runtime.Value = runtime.Value.initNull();
    _ = &reg_16;
    var reg_7: i64 = 0;
    _ = &reg_7;
    var reg_8_storage: runtime.Value = runtime.Value.initNull();
    const reg_8: *runtime.Value = &reg_8_storage;
    _ = &reg_8;

    // Instructions
    // simple_aot_test.php:16
    // simple_aot_test.php:8
    // simple_aot_test.php:7
    // simple_aot_test.php:6
    // simple_aot_test.php:4
    reg_0.release(runtime.runtime_allocator);
    reg_0 = runtime.Value.initString(try runtime.PHPString.init(runtime.runtime_allocator, string_table[0]));
    // simple_aot_test.php:4
    _ = try runtime.php_echo(reg_0);
    if (runtime.hasException()) {
        // Cleanup on exception
        reg_17.*.release(runtime.runtime_allocator);
        reg_8.*.release(runtime.runtime_allocator);
        reg_4.*.release(runtime.runtime_allocator);
        reg_2.*.release(runtime.runtime_allocator);
        reg_0.release(runtime.runtime_allocator);
        reg_9.release(runtime.runtime_allocator);
        reg_11.release(runtime.runtime_allocator);
        reg_12.release(runtime.runtime_allocator);
        reg_13.release(runtime.runtime_allocator);
        reg_16.release(runtime.runtime_allocator);
        reg_18.release(runtime.runtime_allocator);
        reg_19.release(runtime.runtime_allocator);
        reg_20.release(runtime.runtime_allocator);
        reg_21.release(runtime.runtime_allocator);
        reg_22.release(runtime.runtime_allocator);
        return error.RuntimeError;
    }
    // simple_aot_test.php:6
    reg_1 = 10;
    // simple_aot_test.php:6
    reg_2.release(runtime.runtime_allocator);
    runtime.val_assign(reg_2, runtime.Value.initInt(reg_1));
    // simple_aot_test.php:7
    reg_3 = 20;
    // simple_aot_test.php:7
    reg_4.release(runtime.runtime_allocator);
    runtime.val_assign(reg_4, runtime.Value.initInt(reg_3));
    // simple_aot_test.php:8
    reg_5 = runtime.val_deref(reg_2).*.asInt();
    // simple_aot_test.php:8
    reg_6 = runtime.val_deref(reg_4).*.asInt();
    // simple_aot_test.php:8
    reg_7 = reg_5 + reg_6;
    // simple_aot_test.php:8
    reg_8.release(runtime.runtime_allocator);
    runtime.val_assign(reg_8, runtime.Value.initInt(reg_7));
    // simple_aot_test.php:10
    reg_9.release(runtime.runtime_allocator);
    reg_9 = runtime.Value.initString(try runtime.PHPString.init(runtime.runtime_allocator, string_table[4]));
    // simple_aot_test.php:10
    reg_10 = runtime.val_deref(reg_8).*.asInt();
    // simple_aot_test.php:10
    reg_11.release(runtime.runtime_allocator);
    reg_11 = try runtime.php_concat(reg_9, runtime.Value.initInt(reg_10), runtime.runtime_allocator);
    // simple_aot_test.php:10
    reg_12.release(runtime.runtime_allocator);
    reg_12 = runtime.Value.initString(try runtime.PHPString.init(runtime.runtime_allocator, string_table[5]));
    // simple_aot_test.php:10
    reg_13.release(runtime.runtime_allocator);
    reg_13 = try runtime.php_concat(reg_11, reg_12, runtime.runtime_allocator);
    // simple_aot_test.php:10
    _ = try runtime.php_echo(reg_13);
    if (runtime.hasException()) {
        // Cleanup on exception
        reg_17.*.release(runtime.runtime_allocator);
        reg_8.*.release(runtime.runtime_allocator);
        reg_4.*.release(runtime.runtime_allocator);
        reg_2.*.release(runtime.runtime_allocator);
        reg_0.release(runtime.runtime_allocator);
        reg_9.release(runtime.runtime_allocator);
        reg_11.release(runtime.runtime_allocator);
        reg_12.release(runtime.runtime_allocator);
        reg_13.release(runtime.runtime_allocator);
        reg_16.release(runtime.runtime_allocator);
        reg_18.release(runtime.runtime_allocator);
        reg_19.release(runtime.runtime_allocator);
        reg_20.release(runtime.runtime_allocator);
        reg_21.release(runtime.runtime_allocator);
        reg_22.release(runtime.runtime_allocator);
        return error.RuntimeError;
    }
    // simple_aot_test.php:16
    reg_14 = 5;
    // simple_aot_test.php:16
    reg_15 = 3;
    // simple_aot_test.php:16
    reg_16.release(runtime.runtime_allocator);
    reg_16 = try @"add"(runtime.Value.initNull(), &[_]runtime.Value{ runtime.Value.initInt(reg_14), runtime.Value.initInt(reg_15) }, runtime.runtime_allocator);
    if (runtime.hasException()) {
        // Cleanup on exception
        reg_17.*.release(runtime.runtime_allocator);
        reg_8.*.release(runtime.runtime_allocator);
        reg_4.*.release(runtime.runtime_allocator);
        reg_2.*.release(runtime.runtime_allocator);
        reg_0.release(runtime.runtime_allocator);
        reg_9.release(runtime.runtime_allocator);
        reg_11.release(runtime.runtime_allocator);
        reg_12.release(runtime.runtime_allocator);
        reg_13.release(runtime.runtime_allocator);
        reg_16.release(runtime.runtime_allocator);
        reg_18.release(runtime.runtime_allocator);
        reg_19.release(runtime.runtime_allocator);
        reg_20.release(runtime.runtime_allocator);
        reg_21.release(runtime.runtime_allocator);
        reg_22.release(runtime.runtime_allocator);
        return error.RuntimeError;
    }
    // simple_aot_test.php:16
    reg_17.release(runtime.runtime_allocator);
    reg_16.retain();
    runtime.val_assign(reg_17, reg_16);
    // simple_aot_test.php:17
    reg_18.release(runtime.runtime_allocator);
    reg_18 = runtime.Value.initString(try runtime.PHPString.init(runtime.runtime_allocator, string_table[10]));
    // simple_aot_test.php:17
    reg_19.release(runtime.runtime_allocator);
    reg_19 = runtime.val_deref(reg_17).*;
    reg_19.retain();
    // simple_aot_test.php:17
    reg_20.release(runtime.runtime_allocator);
    reg_20 = try runtime.php_concat(reg_18, reg_19, runtime.runtime_allocator);
    // simple_aot_test.php:17
    reg_21.release(runtime.runtime_allocator);
    reg_21 = runtime.Value.initString(try runtime.PHPString.init(runtime.runtime_allocator, string_table[5]));
    // simple_aot_test.php:17
    reg_22.release(runtime.runtime_allocator);
    reg_22 = try runtime.php_concat(reg_20, reg_21, runtime.runtime_allocator);
    // simple_aot_test.php:17
    _ = try runtime.php_echo(reg_22);
    if (runtime.hasException()) {
        // Cleanup on exception
        reg_17.*.release(runtime.runtime_allocator);
        reg_8.*.release(runtime.runtime_allocator);
        reg_4.*.release(runtime.runtime_allocator);
        reg_2.*.release(runtime.runtime_allocator);
        reg_0.release(runtime.runtime_allocator);
        reg_9.release(runtime.runtime_allocator);
        reg_11.release(runtime.runtime_allocator);
        reg_12.release(runtime.runtime_allocator);
        reg_13.release(runtime.runtime_allocator);
        reg_16.release(runtime.runtime_allocator);
        reg_18.release(runtime.runtime_allocator);
        reg_19.release(runtime.runtime_allocator);
        reg_20.release(runtime.runtime_allocator);
        reg_21.release(runtime.runtime_allocator);
        reg_22.release(runtime.runtime_allocator);
        return error.RuntimeError;
    }

    // Cleanup: release allocated values (except return value)
    reg_17.*.release(runtime.runtime_allocator);
    reg_8.*.release(runtime.runtime_allocator);
    reg_4.*.release(runtime.runtime_allocator);
    reg_2.*.release(runtime.runtime_allocator);
    reg_0.release(runtime.runtime_allocator);
    reg_9.release(runtime.runtime_allocator);
    reg_11.release(runtime.runtime_allocator);
    reg_12.release(runtime.runtime_allocator);
    reg_13.release(runtime.runtime_allocator);
    reg_16.release(runtime.runtime_allocator);
    reg_18.release(runtime.runtime_allocator);
    reg_19.release(runtime.runtime_allocator);
    reg_20.release(runtime.runtime_allocator);
    reg_21.release(runtime.runtime_allocator);
    reg_22.release(runtime.runtime_allocator);
    return runtime.Value.initNull();
}

pub fn @"select"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_select_builtin(ctx, args, allocator);
}

pub fn @"go"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_go(ctx, args, allocator);
}

pub fn @"go_wait_all"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_go_wait_all(ctx, args, allocator);
}

pub fn @"go_join"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_go_join(ctx, args, allocator);
}

pub fn @"get_class_methods"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_get_class_methods_builtin(ctx, args, allocator);
}

pub fn @"get_class_vars"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_get_class_vars_builtin(ctx, args, allocator);
}

pub fn @"get_object_vars"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_get_object_vars_builtin(ctx, args, allocator);
}

pub fn @"get_called_class"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_get_called_class_builtin(ctx, args, allocator);
}

pub fn @"forward_static_call"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_forward_static_call_builtin(ctx, args, allocator);
}

pub fn @"forward_static_call_array"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_forward_static_call_array_builtin(ctx, args, allocator);
}

fn registerAllClasses(allocator: std.mem.Allocator) !void {
    try runtime.ClassMeta.registerExceptionClass(allocator);
}

fn registerAllFunctions() !void {
    try runtime.registerUserFunction("add", @"add");
}

pub fn main() !void {
    const allocator = std.heap.page_allocator;
    
    runtime.initRuntime(allocator);
    defer runtime.deinitRuntime();
    
    // 注册所有类
    registerAllClasses(allocator) catch {};
    // 注册所有函数
    registerAllFunctions() catch {};
    defer runtime.cleanupAllClasses();
    
    _ = try @"__main__"(runtime.Value.initNull(), &[_]runtime.Value{}, allocator);
    _ = runtime.php_go_wait_all(runtime.Value.initNull(), &[_]runtime.Value{}, allocator) catch {};
}
