// Generated by zig-php AOT compiler
// DO NOT EDIT

const std = @import("std");
const runtime = @import("runtime_lib.zig");

// String table
const string_table = [_][]const u8{
    "Config",
    "A",
    "B",
    "$x",
    "Result: ",
    "\n",
    "$a",
    "$b",
    "$c",
    "Sum: ",
    "$d",
    "Product: ",
};


pub fn @"__main__"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) !runtime.Value {
    _ = &ctx;
    _ = &args;
    _ = allocator;
    _ = runtime;
    runtime.profiler.enterGlobal("__main__");
    defer runtime.profiler.exitGlobal("__main__");
    // Register declarations
    var reg_20: i64 = 0;
    _ = &reg_20;
    var reg_12: i64 = 0;
    _ = &reg_12;
    var reg_21_storage: runtime.Value = runtime.Value.initNull();
    var reg_21: *runtime.Value = &reg_21_storage;
    _ = &reg_21;
    var reg_9: i64 = 0;
    _ = &reg_9;
    var reg_19: runtime.Value = runtime.Value.initNull();
    _ = &reg_19;
    var reg_2: runtime.Value = runtime.Value.initNull();
    _ = &reg_2;
    var reg_3: i64 = 0;
    _ = &reg_3;
    var reg_1_storage: runtime.Value = runtime.Value.initNull();
    var reg_1: *runtime.Value = &reg_1_storage;
    _ = &reg_1;
    var reg_22: runtime.Value = runtime.Value.initNull();
    _ = &reg_22;
    var reg_25: runtime.Value = runtime.Value.initNull();
    _ = &reg_25;
    var reg_15: runtime.Value = runtime.Value.initNull();
    _ = &reg_15;
    var reg_13: i64 = 0;
    _ = &reg_13;
    var reg_11: i64 = 0;
    _ = &reg_11;
    var reg_7: i64 = 0;
    _ = &reg_7;
    var reg_8_storage: runtime.Value = runtime.Value.initNull();
    var reg_8: *runtime.Value = &reg_8_storage;
    _ = &reg_8;
    var reg_10_storage: runtime.Value = runtime.Value.initNull();
    var reg_10: *runtime.Value = &reg_10_storage;
    _ = &reg_10;
    var reg_26: runtime.Value = runtime.Value.initNull();
    _ = &reg_26;
    var reg_17: runtime.Value = runtime.Value.initNull();
    _ = &reg_17;
    var reg_14_storage: runtime.Value = runtime.Value.initNull();
    var reg_14: *runtime.Value = &reg_14_storage;
    _ = &reg_14;
    var reg_23: i64 = 0;
    _ = &reg_23;
    var reg_0: i64 = 0;
    _ = &reg_0;
    var reg_4: runtime.Value = runtime.Value.initNull();
    _ = &reg_4;
    var reg_6: runtime.Value = runtime.Value.initNull();
    _ = &reg_6;
    var reg_18: runtime.Value = runtime.Value.initNull();
    _ = &reg_18;
    var reg_5: runtime.Value = runtime.Value.initNull();
    _ = &reg_5;
    var reg_16: i64 = 0;
    _ = &reg_16;
    var reg_24: runtime.Value = runtime.Value.initNull();
    _ = &reg_24;

    // Instructions
    // test_fastpath.php:11
    // test_fastpath.php:15
    // test_fastpath.php:16
    // test_fastpath.php:17
    // test_fastpath.php:21
    // test_fastpath.php:11
    reg_0 = 44;
    // test_fastpath.php:11
    reg_1.release(runtime.runtime_allocator);
    runtime.val_assign(reg_1, runtime.Value.initInt(reg_0));
    // test_fastpath.php:12
    reg_2.release(runtime.runtime_allocator);
    reg_2 = runtime.Value.initString(runtime.PHPString.initStatic(string_table[4]));
    // test_fastpath.php:12
    reg_3 = runtime.val_deref(reg_1).*.asInt();
    // test_fastpath.php:12
    reg_4.release(runtime.runtime_allocator);
    reg_4 = try runtime.php_concat(reg_2, runtime.Value.initInt(reg_3), runtime.runtime_allocator);
    // test_fastpath.php:12
    reg_5.release(runtime.runtime_allocator);
    reg_5 = runtime.Value.initString(runtime.PHPString.initStatic(string_table[5]));
    // test_fastpath.php:12
    reg_6.release(runtime.runtime_allocator);
    reg_6 = try runtime.php_concat(reg_4, reg_5, runtime.runtime_allocator);
    // test_fastpath.php:12
    _ = try runtime.php_echo(reg_6);
    if (runtime.hasException()) {
        @branchHint(.unlikely);
        // Cleanup on exception
        reg_2.release(runtime.runtime_allocator);
        reg_4.release(runtime.runtime_allocator);
        reg_5.release(runtime.runtime_allocator);
        reg_6.release(runtime.runtime_allocator);
        reg_15.release(runtime.runtime_allocator);
        reg_17.release(runtime.runtime_allocator);
        reg_18.release(runtime.runtime_allocator);
        reg_19.release(runtime.runtime_allocator);
        reg_22.release(runtime.runtime_allocator);
        reg_24.release(runtime.runtime_allocator);
        reg_25.release(runtime.runtime_allocator);
        reg_26.release(runtime.runtime_allocator);
        return error.RuntimeError;
    }
    // test_fastpath.php:15
    reg_7 = 10;
    // test_fastpath.php:15
    reg_8.release(runtime.runtime_allocator);
    runtime.val_assign(reg_8, runtime.Value.initInt(reg_7));
    // test_fastpath.php:16
    reg_9 = 20;
    // test_fastpath.php:16
    reg_10.release(runtime.runtime_allocator);
    runtime.val_assign(reg_10, runtime.Value.initInt(reg_9));
    // test_fastpath.php:17
    reg_11 = runtime.val_deref(reg_8).*.asInt();
    // test_fastpath.php:17
    reg_12 = runtime.val_deref(reg_10).*.asInt();
    // test_fastpath.php:17
    reg_13 = reg_11 + reg_12;
    // test_fastpath.php:17
    reg_14.release(runtime.runtime_allocator);
    runtime.val_assign(reg_14, runtime.Value.initInt(reg_13));
    // test_fastpath.php:18
    reg_15.release(runtime.runtime_allocator);
    reg_15 = runtime.Value.initString(runtime.PHPString.initStatic(string_table[9]));
    // test_fastpath.php:18
    reg_16 = runtime.val_deref(reg_14).*.asInt();
    // test_fastpath.php:18
    reg_17.release(runtime.runtime_allocator);
    reg_17 = try runtime.php_concat(reg_15, runtime.Value.initInt(reg_16), runtime.runtime_allocator);
    // test_fastpath.php:18
    reg_18.release(runtime.runtime_allocator);
    reg_18 = runtime.Value.initString(runtime.PHPString.initStatic(string_table[5]));
    // test_fastpath.php:18
    reg_19.release(runtime.runtime_allocator);
    reg_19 = try runtime.php_concat(reg_17, reg_18, runtime.runtime_allocator);
    // test_fastpath.php:18
    _ = try runtime.php_echo(reg_19);
    if (runtime.hasException()) {
        @branchHint(.unlikely);
        // Cleanup on exception
        reg_2.release(runtime.runtime_allocator);
        reg_4.release(runtime.runtime_allocator);
        reg_5.release(runtime.runtime_allocator);
        reg_6.release(runtime.runtime_allocator);
        reg_15.release(runtime.runtime_allocator);
        reg_17.release(runtime.runtime_allocator);
        reg_18.release(runtime.runtime_allocator);
        reg_19.release(runtime.runtime_allocator);
        reg_22.release(runtime.runtime_allocator);
        reg_24.release(runtime.runtime_allocator);
        reg_25.release(runtime.runtime_allocator);
        reg_26.release(runtime.runtime_allocator);
        return error.RuntimeError;
    }
    // test_fastpath.php:21
    reg_20 = 30;
    // test_fastpath.php:21
    reg_21.release(runtime.runtime_allocator);
    runtime.val_assign(reg_21, runtime.Value.initInt(reg_20));
    // test_fastpath.php:22
    reg_22.release(runtime.runtime_allocator);
    reg_22 = runtime.Value.initString(runtime.PHPString.initStatic(string_table[11]));
    // test_fastpath.php:22
    reg_23 = runtime.val_deref(reg_21).*.asInt();
    // test_fastpath.php:22
    reg_24.release(runtime.runtime_allocator);
    reg_24 = try runtime.php_concat(reg_22, runtime.Value.initInt(reg_23), runtime.runtime_allocator);
    // test_fastpath.php:22
    reg_25.release(runtime.runtime_allocator);
    reg_25 = runtime.Value.initString(runtime.PHPString.initStatic(string_table[5]));
    // test_fastpath.php:22
    reg_26.release(runtime.runtime_allocator);
    reg_26 = try runtime.php_concat(reg_24, reg_25, runtime.runtime_allocator);
    // test_fastpath.php:22
    _ = try runtime.php_echo(reg_26);
    if (runtime.hasException()) {
        @branchHint(.unlikely);
        // Cleanup on exception
        reg_2.release(runtime.runtime_allocator);
        reg_4.release(runtime.runtime_allocator);
        reg_5.release(runtime.runtime_allocator);
        reg_6.release(runtime.runtime_allocator);
        reg_15.release(runtime.runtime_allocator);
        reg_17.release(runtime.runtime_allocator);
        reg_18.release(runtime.runtime_allocator);
        reg_19.release(runtime.runtime_allocator);
        reg_22.release(runtime.runtime_allocator);
        reg_24.release(runtime.runtime_allocator);
        reg_25.release(runtime.runtime_allocator);
        reg_26.release(runtime.runtime_allocator);
        return error.RuntimeError;
    }

    // Cleanup: release allocated values (except return value)
    reg_1.*.release(runtime.runtime_allocator);
    reg_8.*.release(runtime.runtime_allocator);
    reg_10.*.release(runtime.runtime_allocator);
    reg_14.*.release(runtime.runtime_allocator);
    reg_21.*.release(runtime.runtime_allocator);
    reg_2.release(runtime.runtime_allocator);
    reg_4.release(runtime.runtime_allocator);
    reg_5.release(runtime.runtime_allocator);
    reg_6.release(runtime.runtime_allocator);
    reg_15.release(runtime.runtime_allocator);
    reg_17.release(runtime.runtime_allocator);
    reg_18.release(runtime.runtime_allocator);
    reg_19.release(runtime.runtime_allocator);
    reg_22.release(runtime.runtime_allocator);
    reg_24.release(runtime.runtime_allocator);
    reg_25.release(runtime.runtime_allocator);
    reg_26.release(runtime.runtime_allocator);
    return runtime.Value.initNull();
}

pub fn @"select"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_select_builtin(ctx, args, allocator);
}

pub fn @"go"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_go(ctx, args, allocator);
}

pub fn @"go_wait_all"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_go_wait_all(ctx, args, allocator);
}

pub fn @"go_join"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_go_join(ctx, args, allocator);
}

pub fn @"get_class_methods"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_get_class_methods_builtin(ctx, args, allocator);
}

pub fn @"get_class_vars"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_get_class_vars_builtin(ctx, args, allocator);
}

pub fn @"get_object_vars"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_get_object_vars_builtin(ctx, args, allocator);
}

pub fn @"get_called_class"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_get_called_class_builtin(ctx, args, allocator);
}

pub fn @"forward_static_call"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_forward_static_call_builtin(ctx, args, allocator);
}

pub fn @"forward_static_call_array"(ctx: runtime.Value, args: []const runtime.Value, allocator: std.mem.Allocator) anyerror!runtime.Value {
    return runtime.php_forward_static_call_array_builtin(ctx, args, allocator);
}

fn registerAllClasses(allocator: std.mem.Allocator) !void {
    try runtime.ClassMeta.registerExceptionClass(allocator);
    const Config_meta = try runtime.ClassMeta.init(allocator, "Config");
    try runtime.registerClass(Config_meta);
    _ = try runtime.php_set_static_property("Config", "A", runtime.Value.initInt(42));
    _ = try runtime.php_set_static_property("Config", "B", runtime.Value.initInt(2));
    if (Config_meta.findMethod("__construct")) |m| { Config_meta.magic_construct = m.func; }
    if (Config_meta.findMethod("__destruct")) |m| { Config_meta.magic_destruct = m.func; }
    if (Config_meta.findMethod("__get")) |m| { Config_meta.magic_get = m.func; }
    if (Config_meta.findMethod("__set")) |m| { Config_meta.magic_set = m.func; }
    if (Config_meta.findMethod("__call")) |m| { Config_meta.magic_call = m.func; }
    if (Config_meta.findMethod("__callStatic")) |m| { Config_meta.magic_callStatic = m.func; }
    if (Config_meta.findMethod("__sleep")) |m| { Config_meta.magic_sleep = m.func; }
    if (Config_meta.findMethod("__wakeup")) |m| { Config_meta.magic_wakeup = m.func; }
    if (Config_meta.findMethod("__serialize")) |m| { Config_meta.magic_serialize = m.func; }
    if (Config_meta.findMethod("__unserialize")) |m| { Config_meta.magic_unserialize = m.func; }
}

fn registerAllFunctions() !void {
}

pub fn main() !void {
    const allocator = std.heap.page_allocator;
    
    runtime.initRuntime(allocator);
    defer runtime.deinitRuntime();

    var profiling_enabled: bool = false;
    if (std.process.getEnvVarOwned(allocator, "ZIGPHP_PROFILE")) |v| {
        profiling_enabled = true;
        allocator.free(v);
    } else |_| {}

    var profiler: runtime.profiler.Profiler = undefined;
    var generator: runtime.flamegraph.FlameGraphGenerator = undefined;

    if (profiling_enabled) {
        profiler = try runtime.profiler.Profiler.init(allocator, .custom);
        profiler.enable();
        runtime.profiler.setGlobalProfiler(&profiler);

        generator = try runtime.flamegraph.FlameGraphGenerator.init(allocator, &profiler);
        generator.setMinDisplayTime(0);
        if (std.process.getEnvVarOwned(allocator, "ZIGPHP_PROFILE_INTERVAL_NS")) |s| {
            defer allocator.free(s);
            generator.setSamplingInterval(std.fmt.parseInt(u64, s, 10) catch generator.sampling_interval_ns);
        } else |_| {}
        try generator.startSampling();
    }

    defer if (profiling_enabled) {
        generator.stopSampling();

        const folded = generator.generateFoldedFormat(allocator) catch null;
        if (folded) |data| {
            defer allocator.free(data);
            const out = std.fs.cwd().createFile("flamegraph.txt", .{}) catch null;
            if (out) |file| {
                defer file.close();
                _ = file.writeAll(data) catch {};
            }
        }

        const pb = std.fs.cwd().createFile("profile.pb", .{}) catch null;
        if (pb) |file| {
            defer file.close();
            var buf: [16 * 1024]u8 = undefined;
            var w = file.writer(&buf);
            runtime.pprof.writeCpuProfileFromFlameGraph(allocator, &w.interface, generator.root, generator.sampling_interval_ns) catch {};
            _ = w.end() catch {};
        }

        generator.deinit();
        runtime.profiler.setGlobalProfiler(null);
        profiler.deinit();
    };
    
    // 注册所有类
    registerAllClasses(allocator) catch {};
    // 注册所有函数
    registerAllFunctions() catch {};
    defer runtime.cleanupAllClasses();
    
    _ = try @"__main__"(runtime.Value.initNull(), &[_]runtime.Value{}, allocator);
    _ = runtime.php_go_wait_all(runtime.Value.initNull(), &[_]runtime.Value{}, allocator) catch {};
}
